### ISSUE TITLE
Show path of gradle file containing the dependencies (or the module name)

### ISSUE THREAD

**Issue by frmz** [ben-manes/gradle-versions-plugin#101]
I have a project with a lot of modules and i always need to grep around to understand where the upgradable dep is, would it be possible to show the path(s) of the gradle files with the upgradable deps? Or the module name if the file is hard to get.

**Comment by ben-manes** [comment]
This is similar to #70. It would have to be a report option of either a flat or grouped listing.

For large projects you should consider centralizing your dependency definitions, e.g. [dependencies.gradle](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle). Then a flat list is preferred and it reduces having modules use different versions due to copy and pasting.

**Comment by frmz** [comment]
My problem is that depending on the build target some modules are excluded so i cannot move the deps out of the module itself, but yes, this is definitely similar to #70 we can set it as a dupe if you like

**Comment by vanniktech** [comment]
Closing in favor of #70

**Comment by Vampire** [comment]
Either this or #70 (or both) would be nice, but closing this in favor of #70 and at the same time closing #70 seems bad. :-(

**Comment by Vampire** [comment]
Actually all three are nice ideas. Maybe you needed some option or configurable closure on how to group or similar. 
For some it would be nice to have the grouping like now and just have the location(s) where the dependency is.
For others it might be nicer to group by module. 
In my opinion the separation of build dependencies vs. project dependencies should always be done, independent of any other grouping as those are semantically different projects, one project is building the real project and the other project is the real project itself.
