### ISSUE TITLE
Question: is it possible to make it more UI-friendly ?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ben-manes/gradle-versions-plugin#107]
I find it quite annoying to scroll through the console texts to find this information, which also most of the times even need to be ignored if no new version is available for all repos the project has.

Is it possible to make something in the IDE itself (notification, popup, dialog, red-underline...), whenever a new version of a repo is found?

**Comment by ben-manes** [comment]
The analysis can be a little slow due to Gradle not supporting parallel resolution, so it resolves each lookup as sequential http calls. That's not bad when you run it periodically, but poor enough that you wouldn't want it as part of the build. So I'd imagine it could be annoying if an IDE background task blocked you from compiling. That said, there is an [IntelliJ plugin](https://github.com/takuaraki/DependenciesVersionChecker) that tries to inject this one and scrape the output.

A better solution is if you are using a CI server and can script a job to send a notification. This was discussed in #54 where a user leveraged Jenkin's Text Finder Plugin. This [blog post](http://blog.octo.com/en/keep-your-gradle-dependencies-up-to-date-seamlessly/) makes a similar suggestion, though they don't filter to ignore if no updates were found. You might prefer the json, xml, or closure outputs instead of the default console one.

Otherwise you might have to use a different tool. A open-source / commercial option is VersionEye. When I tried their auto discovery of Gradle projects was poor, but you can now get around that by using a [plugin](https://github.com/stempler/gradle-versioneye-plugin) to upload your dependency graph to their servers. It seems there are a bunch of similar services out there, though it seems weird to pay for a basic feature of a build tool. I think most people just script a CI job if they want to be fancy.

**Comment by AndroidDeveloperLB** [comment]
That's too bad. I just wish something that's automatic for me, just like "new version of Android-Studio is available", or at something in the gradle files, to mark which repos have updates (as Google have for its services).

**Comment by ben-manes** [comment]
Those are hardcoded lookups instead of a more generic check. Regardless it's out of scope for the plugin to provide, you'd have to request it from the vendors.

**Comment by AndroidDeveloperLB** [comment]
Sorry. And thank you for trying to help.
