### ISSUE TITLE
Fails to check gradle.plugin.com.srcclr:gradle 

### ISSUE THREAD

**Issue by ncd7** [ben-manes/gradle-versions-plugin#112]
The way I use the ```gradle.plugin.com.srcclr:gradle``` plugin is in my root build.properties:
```
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://plugins.gradle.org/m2/" // required by gradle_plugins.source_clear
        }
    }
    apply from: "${rootDir}/dependencies.gradle"
    dependencies {
        classpath gradle_plugins.source_clear
        // others
    }
}
```
where ```source_clear: dependencies.create(group: 'gradle.plugin.com.srcclr', name:'gradle', version: gradle_plugin_versions.SOURCE_CLEAR_PLUGIN)``` where ```SOURCE_CLEAR_PLUGIN: '2.0.1'```

The ```dependencyUpdates``` task gives the following error
```
      <unresolvedDependency>
        <name>gradle</name>
        <group>gradle.plugin.com.srcclr</group>
        <version>2.0.1</version>
        <reason>Could not find any matches for gradle.plugin.com.srcclr:gradle:+ as no versions of gradle.plugin.com.srcclr:gradle are available.&#xd;
Searched in the following locations:&#xd;
    https://jcenter.bintray.com/gradle/plugin/com/srcclr/gradle/maven-metadata.xml&#xd;
    https://jcenter.bintray.com/gradle/plugin/com/srcclr/gradle/&#xd;
    https://plugins.gradle.org/m2/gradle/plugin/com/srcclr/gradle/maven-metadata.xml&#xd;
    https://plugins.gradle.org/m2/gradle/plugin/com/srcclr/gradle/</reason>
      </unresolvedDependency>
```

Additionally, I use following task configuration (basically from the wiki example). I tried commenting out the resolution strategy just in case but the issue persists.

```
dependencyUpdates {
    // ensure release candidate versions (eg rc, alpha, beta, etc) are not considered legitimate upgrade targets
    resolutionStrategy = {
        componentSelection { rules ->
            rules.all { ComponentSelection selection ->
                boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
                    selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
                }
                if (rejected) {
                    selection.reject('Release candidate')
                }
            }
        }
    }

    revision = 'release'
    outputFormatter = 'plain,xml'
}
```

**Comment by ben-manes** [comment]
Unfortunately the Gradle plugin repository does not act like a normal maven repository. For instance it sometimes will not expose a `maven-metadata.xml` or when it does, it is outdated because they do not update it after a release. Despite multiple requests to resolve these issues, the Gradle team has been silent and ignored those requests. There isn't anything that I can do about it and instead ask users to bring it up on their forum to incentivize the fix.

This plugin scripts Gradle's own dependency management, which gives us a lot of flexibility and avoids duplicating their work. Unfortunately if Gradle itself cannot resolve with their repository restrictions, we can't be expected to do any better.

**Comment by ncd7** [comment]
i see, thanks @ben-manes . could you point me to the exact forum where i can raise the issue?

**Comment by ben-manes** [comment]
The [Gradle forum](https://discuss.gradle.org/c/help-discuss/plugin-portal) is the ideal location. I've also tried asking on [gradle-dev](https://groups.google.com/forum/#!forum/gradle-dev).

**Comment by ncd7** [comment]
thanks a ton
