### ISSUE TITLE
[Enhancement] Option to fail build upon outdated dependencies + ignore list

### ISSUE THREAD

**Issue by ncd7** [ben-manes/gradle-versions-plugin#113]
It would be great to have the ability to configure the task to fail if any outdated dependencies are found. Additionally, the ability to specify a list of dependencies to ignore from the check would go great with this feature.

I realize this request is a bit of a feature creep as the intent is probably for other tools to consume the output. However, I think this is a very basic type of behavior that most that use this plugin would want, without taking on the burden of yet another tool for anything more sophisticated. I think it's a very natural extension to using this plugin.

**Comment by ben-manes** [comment]
> It would be great to have the ability to configure the task to fail if any outdated dependencies are found.

Since resolution can be slow (due to Gradle not parallelizing it), you would typically run the task manually or on a CI job. It wouldn't be part of a normal build. Instead you can have a CI job run periodically that performs that task (e.g. [Jenkins example](http://blog.octo.com/en/keep-your-gradle-dependencies-up-to-date-seamlessly/)). The [gradle-update-notifier](https://github.com/y-yagi/gradle-update-notifier) is one user's approach, which he kindly open sourced.

If you really do want it as part of the build, you can use the closure outputFormatter (see example in #74) and fail the build if updates were discovered.

> Additionally, the ability to specify a list of dependencies to ignore from the check would go great with this feature.

This should be possible using a resolutionStrategy (the one scoped to only the dependencyUpdates task). For your list of ignored dependencies, you would either force any resolution to the declared version or force the current version to the latest (e.g. `+`). Either way, the task will compare the declared and update versions, see that they are the same, and include it in the up-to-date list.

> I realize this request is a bit of a feature creep...

My concern is becoming a blocker, since the first release was all I needed to satisfy my needs. If a task can't be done due to a limitation then I'll try to resolve that gap. Otherwise I hope more users will blog and open-source their solutions.

**Comment by ncd7** [comment]
thanks for the rapid reply, this is useful. it doesn't bother me that it takes longer right now, though i certainly would not want it for **local** builds. I already have logic to detect if i'm running on a CI server, so in that case i can install a conditional closure to fail the build if updatables are found. I'm ok with it running each time a CI build occurs (at least for the moment).

for the ignored lists i'll follow your advice on the resoln strategy, or i might even bake it into the closure. 

i'll close the issue as i think this is pretty good. 

BTW since this is likely a common request (or i would imagine it is), it might be good to add a section to the README or wiki that outlines these 'advanced' options since the core plugin is rich enough to accommodate them + links to user solutions.

**Comment by ben-manes** [comment]
Due to the Gradle cache, its only slow once per day (the default expiry time). The performance would improve when [GRADLE-2582](https://issues.gradle.org/browse/GRADLE-2582) is resolved.

When you have something working nicely, please send a PR with your notes. I'll look into adding the section in the meantime.
