### ISSUE TITLE
Check parameterized dependencies version

### ISSUE THREAD

**Issue by josetesan** [ben-manes/gradle-versions-plugin#114]
If can be helpful if yhe plugin could check any given group's version,

Something like 'gradle dependencyUpdates --groupId='org.slf4j'  will check updates only on these artifacts

**Comment by ben-manes** [comment]
Does piping into grep solve this adequately?

**Comment by josetesan** [comment]
Absolutely, but i was proposing this mainly for performance benefits . The usual Spring-boot brings up so many dependencies it can take a lot of time to check . 

Get Outlook for iOS




On Wed, Aug 3, 2016 at 6:47 PM +0200, "Ben Manes" <notifications@github.com> wrote:












Does piping into grep solve this adequately?

**Comment by ben-manes** [comment]
I figured it was due to performance, which I'm inclined to not handle and defer to Gradle. Since this plugin is scripting its dependency management capabilities, the issue would be resolved if [GRADLE-2582](https://issues.gradle.org/browse/GRADLE-2582) was implemented. The challenge is finding ways to incentivize the Gradle team to tackle their backlog.

**Comment by josetesan** [comment]
ok, thanks ben

2016-08-03 19:55 GMT+02:00 Ben Manes <notifications@github.com>:

**Comment by ben-manes** [comment]
Supposedly Gradle 4 has parallel resolution, though it's still not too speedy for me. Hopefully it will improve over releases.
