### ISSUE TITLE
Failed to determine latest version

### ISSUE THREAD

**Issue by johnkil** [ben-manes/gradle-versions-plugin#118]
Comparing dependency (current: com.appsflyer:af-android-sdk:4.5.0, latest: 4.5.0). 
But latest version 4.6.0 (

**Comment by ben-manes** [comment]
Can you check if you have a resolution strategy limiting the query?

**Comment by johnkil** [comment]
I have a default resolution strategy. Maven - https://mvnrepository.com/artifact/com.appsflyer/af-android-sdk

**Comment by ben-manes** [comment]
The problem is that you are querying only JCenter, which hosts the [dependency](https://bintray.com/appsflyersdk/maven/com.appsflyer%3Aaf-android-sdk/4.5.0) with a `maven-metadata.xml` stating that `4.5.0` is the latest. If you also include `mavenCentral()` in your repository listing then you'll see `4.6.0` in the report.

**Comment by johnkil** [comment]
@ben-manes thanks, it solved the problem :simple_smile:
