### ISSUE TITLE
Older version listed as update

### ISSUE THREAD

**Issue by gabrielittner** [ben-manes/gradle-versions-plugin#121]
When the version of a dependency ends with `-update1` the version  without that suffix is listed as update for that.

An example for that is (it already has a 1.3 release by now, so you have to ignore that version)
https://repo1.maven.org/maven2/com/jakewharton/auto/value/auto-value-annotations . When you depend on `1.2-update1` the plugin will suggest to update to `1.2`.
Before the 1.3 release the metadata looked like this:

``` xml
<metadata>
  <groupId>com.jakewharton.auto.value</groupId>
  <artifactId>auto-value-annotations</artifactId>
  <versioning>
    <latest>1.2-update1</latest>
    <release>1.2-update1</release>
    <versions>
      <version>1.2</version>
      <version>1.2-update1</version>
    </versions>
    <lastUpdated>20160830215216</lastUpdated>
  </versioning>
</metadata>
```

**Comment by ben-manes** [comment]
I think this is a limitation of Maven's version comparison rules and Gradle's implementation of that. The comparator is probably expecting cases like `-beta` to ignore. Per #73 on the forum, Gradle has some suffixes that it special cases (like RC). I don't know why `latest` isn't an override, though. Its too bad semver wasn't used since those rules don't trigger as many quirks.

You could bring this up on the Gradle Forum and see what the devs say. Since we're delegating to their resolution rules its a limitation in the dependency management.

**Comment by jochenberger** [comment]
I think that the behavior is correct. "1.2-update1" is probably treated as a pre-release version according to the SemVer spec (http://semver.org/spec/v1.0.0.html) item 4.

**Comment by huxi** [comment]
For what it's worth: The Java version scheme, both <=1.8 and >=9, are handling `-postfix` as "less than without prefix", too.

**Comment by ben-manes** [comment]
Closing as it sounds like we're doing the right thing. If not, then please open a Gradle issue as we are using their comparator. You could test in Maven to see how it behaves to verify.
