### ISSUE TITLE
Reported last version of dependencies is outdated

### ISSUE THREAD

**Issue by PLNech** [ben-manes/gradle-versions-plugin#122]
First of all, congratulations for this very helpful plugin! 😄 

When running `dependencyUpdates`, the reported last version of `com:algolia:algoliasearch-android` is **2.5.0**. However, the [last available in `mavenCentral`](https://repo1.maven.org/maven2/com/algolia/algoliasearch-android/3.5.0/) is **3.5.0**, which is also the last tag on GitHub.

What could explain the wrong version being reported? Maybe this is similar to #103?

**Comment by ben-manes** [comment]
The [latest version](https://jcenter.bintray.com/com/algolia/algoliasearch-android/maven-metadata.xml) on jcenter is 2.5.0. If you include mavenCentral it should query and find 3.5.0, but does not query repositories you have not included. You probably need to unlink jcenter to have it mirror central.

**Comment by PLNech** [comment]
Oh, this explains that! 
Thank you, I'll close the issue and check on my side what stopped working in our release process.

**Comment by ben-manes** [comment]
Easiest solution is to delete your repositories on JCenter. When you take ownership of a dependency from Central, that "linking" stops the automatic mirroring and JCenter assumes you will not publish through them. If you do, then you have configure the account to sync with Central by providing your credentials. But if you still publish to Central instead, but took ownership to see the stats, then you'll stop seeing updates to your repositories reflected in JCenter.

I had the same problem with Caffeine, with JCenter reps reaching out because they received complaints and asked if they could unlink. It is a very confusing UX.

My recommendation is to either delete your JCenter repositories or switch the release process to use JCenter with Central sync. The JCenter stats wasn't worth the hassle to change my workflow, so I deleted the remaining ones I had.

**Comment by PLNech** [comment]
It would if we did send it as-is, but see [the setAroundRadius implementation](https://github.com/algolia/algoliasearch-client-android/blob/master/algoliasearch/src/main/java/com/algolia/search/saas/Query.java#L230-L235):

```java
 if (radius == Query.RADIUS_ALL) {
            return set(KEY_AROUND_RADIUS, "all");
 }
```
