### ISSUE TITLE
Plugin latest version not detected

### ISSUE THREAD

**Issue by IonutNegru87** [ben-manes/gradle-versions-plugin#126]
I'm having an issue for Error-prone plugin.
Conform latest documentation and [gradle plugin info](https://plugins.gradle.org/plugin/net.ltgt.errorprone), the latest version is **0.0.8**, but the library detects that the latest version is **0.0.6**:

> - net.ltgt.gradle:gradle-errorprone-plugin [0.0.8 <- 0.0.6]

Any solution or recommendation for this?

**Comment by tbroyer** [comment]
FWIW, 0.0.1 to 0.0.6 were deployed to Central, whereas 0.0.7 and 0.0.8 are only available through the Gradle Plugin Portal.

**Comment by ben-manes** [comment]
The Gradle Plugin Portal is a broken repository and requests to fix it have gone ignored. I have asked both on the Gradle Forum and on the developer Google group. My only recommendation is that you ask them, perhaps as a Github issue which is now allowed. They've ignored it probably because it is an IT mistake and the developers don't manage that.

If I recall correctly, there are two problems. (1) The repository disallows querying the directory to read the `maven-metadata.xml` and (2) the metadata isn't updated when new versions are deployed. Since this plugin is scripting Gradle's resolution handling, this same problem would probably occur if you use `+` as the version number.

**Comment by IonutNegru87** [comment]
I see. I will open a bug on Gradle github, maybe this gets fixed.
Until then, is there a way to ignore that specific library(filtering/blacklist)?

Thank you.

**Comment by ben-manes** [comment]
Please link to this issue if you open one.

You might be able to set the task's resolutionStrategy, but since its a resolution failure that probably won't work...

**Comment by IonutNegru87** [comment]
I see, guess I'll have to ignore it for now :).
I think the issue I opened was referenced automatically. If not, please let me know and I'll add the link manually.

Thank you.

**Comment by TWiStErRob** [comment]
I think the non-support of metadata is intentional, it's likely the means to prevent
```gradle
plugins {
	id 'com.github.ben-manes.versions' version '0.+'
}
```
from working:
```
* What went wrong:
Plugin [id: 'com.github.ben-manes.versions', version: '0.+'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (dynamic plugin versions are not supported)
```

**Comment by ben-manes** [comment]
That's a good bet. I still think it was a mistake to put that restriction, as it does break the repository expectations. By using a client side restriction, e.g. `beforeResolve` check, it would have the intended behavior without deviating from the standards.

**Comment by dalewking** [comment]
See this related bug I reported on another plugin. While there may be issues with how gradle is doing things, I think there is something this plug-in can do.

I think the issue is that gradle is adding a prefix of "gradle.plugin.". If I have for example:

    plugins {
        id "foo-bar"
    }

Then this plugin is going to try to look up "gradle.plugin.foo-bar" in all repositories, which it will not find as it does not exist. What does exist however is the plugin without the "gradle.plugin." prefix.

If this plugin detected the "gradle.plugin." prefix and did a look up without the prefix I think that would fix my issue I reported with retrolambda.

**Comment by ben-manes** [comment]
The actual dependency has the prefix, which is an oddity of the deployment scheme for the plugin portal. See their [buildscript example](https://plugins.gradle.org/plugin/me.tatarka.retrolambda) which resolves using the true coordinates. This doesn't occur for plugins that are released to JCenter with a sync to the plugin portal, like this one, so its a Gradle oddity.

As @vanniktech replied in the other issue, this is probably a Gradle [bug](https://github.com/gradle/gradle/issues/1297). I've asked on multiple occasions and now defer to requesting users bring it up on their github and forum. So if you can nudge them a little, perhaps someone will fix the portal.

**Comment by boris-petrov** [comment]
Same thing happens with `me.champeau.gradle:jmh-gradle-plugin`:

```
 - me.champeau.gradle:jmh-gradle-plugin [0.3.1 <- 0.2.0]
```

Is there any chance for that Gradle bug to be fixed any time soon? :)

**Comment by ben-manes** [comment]
Ask on their bug. They have always been unresponsive regardless of who asks, including a former Gradle developer.

**Comment by ben-manes** [comment]
It appears that Gradle has mostly fixed this problem. However, they did so by special casing gradle plugins that follow a newer syntax during resolution.

A plugin with the group prefix `gradle.plugin` will be resolved correctly. For example,
https://plugins.gradle.org/m2/gradle/plugin/io/morethan/jmhreport/gradle-jmh-report/

This prefix was introduced after the plugin portal, so many early plugins did not get the addition. They appear to fallback to the standard `maven-metadata.xml` lookup, which does not exist on the plugin portal, so the metadata cannot be resolved.
https://plugins.gradle.org/m2/net/ltgt/gradle/gradle-errorprone-plugin/

**Comment by jaredsburrows** [comment]
I just tested this using Gradle `4.5.1` and gradle-versions-plugin `0.17.0` and it works fine:
```
$ gradlew dependencyUpdates

> Task :dependencyUpdates 

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.17.0

The following dependencies have later milestone versions:
 - net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin [0.0.11 -> 0.0.13]

Generated report file build/dependencyUpdates/report.txt


BUILD SUCCESSFUL in 16s
1 actionable task: 1 executed
```

**Comment by jbduncan** [comment]
Glad to hear that things are apparently fixed on Gradle's end! :)

**Comment by ben-manes** [comment]
Interestingly, one has to use either the `plugin` block or the Gradle plugin format if using a `buildscript` block. e.g.

`net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:+` resolves correctly.
`net.ltgt.gradle:gradle-errorprone-plugin:+` does not

So if you still use buildscript, make sure to use the longer format.

**Comment by jbduncan** [comment]
Oh okay, not so good.

I can't be the only one, but it's not obvious to me that coordinates like `net.ltgt.gradle:gradle-errorprone-plugin:+` can be expanded to `net.ltgt.errorprone:net.ltgt.errorprone.gradle.plugin:+`, or what the algorithm for expansion is. I'm almost certain it's not explained in https://plugins.gradle.org/ or the page for a given plugin like https://plugins.gradle.org/plugin/net.ltgt.errorprone.

Should this issue be re-opened, then?

**Comment by ben-manes** [comment]
Its a very weird Gradle quirk. This is how they designed their custom plugin resolver to work, for reasons that I never understood. They finally reverted to a normal maven repository, which is great, but oddly did their own unique thing. I guess in their migration they only backfill the `maven-metadata.xml` when the expansion is detected, since they did not generate that file originally. Hopefully now that the `plugin` block is more powerful there is less of a reason to use the classic approach.

I don't think it is appropriate for us to reverse engineer their expansion algorithm to adapt, as it sounds very hacky. I wish they would have generated the `maven-metadata` for all existing artifacts instead.

**Comment by tbroyer** [comment]
@jbduncan These are plugin marker artifacts: https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers

**Comment by jbduncan** [comment]
Thanks @tbroyer!

**Comment by ben-manes** [comment]
Just verified on 4.6 and the plugin marker artifact issue is no longer a problem. Both variations of the declaration worked for me when resolving.
