### ISSUE TITLE
Versions exceed

### ISSUE THREAD

**Issue by PaulWoitaschek** [ben-manes/gradle-versions-plugin#136]
I have some dependencies it reports as exceeded.

```
The following dependencies exceed the version found at the release revision level:
 - com.bluelinelabs:conductor [2.1.0 <- 2.0.1]
 - com.bluelinelabs:conductor-support [2.1.0 <- 1.1.4]
 - io.reactivex.rxjava2:rxjava [2.0.5 <- 2.0.1]
```

All these newer versions can be found on http://search.maven.org

Also it reports wrong for jsr250
` javax.annotation:jsr250-api [1.0 -> 1.0-20050927.133100]`
But maven reports 1.0 as the higher version, see https://mvnrepository.com/artifact/javax.annotation/jsr250-api/1.0-20050927.133100

**Comment by ben-manes** [comment]
You should include `mavenCentral()` in your repository listing. This plugin uses Gradle's dependency management to perform the resolution, rather than duplicate that effort. It appears that rxjava2 on JCenter is at 2.0.1, but on a miss they resolve (without updating the repo) from Maven Central. So Gradle's query to the repository is given a predecessor release as the latest.

For jsr250, `search.maven.org` [shows](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22jsr250-api%22) 1.0-2.. as the latest. But the [maven-metadata.xml](http://repo1.maven.org/maven2/javax/annotation/jsr250-api/maven-metadata.xml) indicates 1.0. The tie braker would be to see what Maven's version plugin reports. If it states 1.0, then you can file an issue with Gradle for them to investigate.

**Comment by PaulWoitaschek** [comment]
> For jsr250, search.maven.org shows 1.0-2.. as the latest. But the maven-metadata.xml indicates 1.0. The tie braker would be to see what Maven's version plugin reports. If it states 1.0, then you can file an issue with Gradle for them to investigate.

How do I check that?

**Comment by ben-manes** [comment]
Write a simple pom.xml and run `mvn versions:display-dependency-updates`. I think that I did it in the past and maven gave the same answer, but not positive.

**Comment by PaulWoitaschek** [comment]
Thanks for your support.
