### ISSUE TITLE
Version comparison problem? (1.10.2 v. 1.9.1)

### ISSUE THREAD

**Issue by xpe** [ben-manes/gradle-versions-plugin#146]
I'm using "com.github.ben-manes:gradle-versions-plugin:0.14.0".

```
./gradlew dependencyUpdates -Drevision=release
...
The following dependencies exceed the version found at the release revision level:
 - org.jsoup:jsoup [1.10.2 <- 1.9.1]
```

This is incorrect, right?

At present, jsoup 1.10.2 is the latest: https://mvnrepository.com/artifact/org.jsoup/jsoup/1.10.2

Same with:

```
./gradlew dependencyUpdates                   
...
The following dependencies exceed the version found at the milestone revision level:
 - org.jsoup:jsoup [1.10.2 <- 1.9.1]
```

My dependencies include:

```
dependencies {
    compile group: 'org.jsoup', name: 'jsoup', version: '1.10.2'
}
```

**Comment by ben-manes** [comment]
Its because you only have jcenter in your repository list. They're stuck on the [older version](https://bintray.com/jhy/maven/org.jsoup%3Ajsoup) and proxy to Central for unknown versions. Its really annoying.

You should add Central since we respect your repository settings rather than add defaults. That will then find the correct metadata.
