### ISSUE TITLE
Support for RubyGems?

### ISSUE THREAD

**Issue by boris-petrov** [ben-manes/gradle-versions-plugin#155]
We're using the `com.github.jruby-gradle.base` Gradle plugin and are using `JRuby` for our integration tests. That plugin allows us to write something like:

```groovy
configurations {
	rubocop
}

dependencies {
	jrubyExec 'org.jruby:jruby-complete:9.1.8.0'

	jrubyExec 'rubygems:rspec:3.5.0'
	jrubyExec 'rubygems:capybara:2.13.0'

	rubocop 'rubygems:rubocop:0.48.1'
}
```

Unfortunately the Gradle versions plugin cannot check for newer versions of these Ruby gems (the last three lines - for the first one - JRuby itself - it does work). I've no idea how they do this (convert gems into Java packages) so I'm not sure what I'm requesting is even possible, but it doesn't hurt to ask. :)

**Comment by ben-manes** [comment]
Please ask the jruby plugin author. A quick glance and I think the [range conversion](https://github.com/jruby-gradle/jruby-gradle-plugin/blob/master/jruby-gradle-base-plugin/src/main/groovy/com/github/jrubygradle/internal/GemVersion.groovy#L70) only works for `x.+` and not just `+`. I think it's resolving low and high to zero due to no matches.

**Comment by ben-manes** [comment]
Closing as it seems like a ruby-gems issue. @rtyler, et al can reopen if he disagrees.
