### ISSUE TITLE
Treat eap as something before final release

### ISSUE THREAD

**Issue by mg6maciej** [ben-manes/gradle-versions-plugin#161]
```
The following dependencies exceed the version found at the milestone revision level:
 - org.jetbrains.kotlin:kotlin-annotation-processing [1.1.2 <- 1.1.2-eap-77]
 - org.jetbrains.kotlin:kotlin-gradle-plugin [1.1.2 <- 1.1.2-eap-77]
 - org.jetbrains.kotlin:kotlin-reflect [1.1.2 <- 1.1.2-eap-77]
 - org.jetbrains.kotlin:kotlin-stdlib-jre8 [1.1.2 <- 1.1.2-eap-77]
```
JetBrains just likes EAP (early access program) in their libs :)

**Comment by ben-manes** [comment]
Please propose this enhancement to Gradle. See a similar [issue](https://github.com/gradle/gradle/issues/1378) for Spring's `RELEASE` label. Since we delegate to Gradle rather than rewrite their dependency management code, these changes are on their side. That simplifies our code and means using range scans (e.g. `+`) works exactly the same.

You can filter these out locally using a custom `resolutionStragegy`. See the README for an example. That can't change the comparison order, but will reject them if you prefer.
