### ISSUE TITLE
Support parallel maven-metadata file loading

### ISSUE THREAD

**Issue by imanushin** [ben-manes/gradle-versions-plugin#168]
For current moment plugin download available versions one-by-one:
1. All dependencies are processed sequentially
2. All repositories are checked sequentially

It is better to process both lists in parallel, to speedup plugin in the networks with huge latency (however, with normal throughput), such as Singapore location or working under the corporate proxy

**Comment by ben-manes** [comment]
This is because we delegate to Gradle for resolution and I likewise requested parallel support in 2012. There is recent work but it doesn't handle our case (https://github.com/gradle/gradle/issues/1309).

The alternative is to rewrite Gradle's dependency logic, which is not a great solution imho. You could use a virtual repository to proxy for performance, or defer to a CI task to tolerate the wait.

**Comment by imanushin** [comment]
@ben-manes , not good news, however, thank you !

I think, issue can be closed, current solution is fully right
