### ISSUE TITLE
invalid comparison for broken versioning eg. 3.2.2 < 20040616

### ISSUE THREAD

**Issue by hexmind** [ben-manes/gradle-versions-plugin#170]
now: 3.2.2 < 20040616

> The following dependencies have later release versions:
>  - commons-collections:commons-collections [3.2.2 -> 20040616]

expected: 3.2.2 > 20040616

> Version | Repository | Usages | Date
> 3.2.2 | Central | 916 | (Nov, 2015)
> ...
> 20040616 | Central | 20 | (Nov, 2005)
https://mvnrepository.com/artifact/commons-collections/commons-collections

**Comment by ben-manes** [comment]
The official Maven Central site uses maven's version ordering instead of dates and has the same [problem](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22commons-collections%22). It looks like the [maven-metadata.xml](repo1.maven.org/maven2/commons-collections/commons-collections/maven-metadata.xml) is still reporting the bad version as the latest. This means Gradle's evaluation is on par with Maven's.

The fix then is that you can use a resolution strategy to reject this version in the report.

Alternatively, use the newer dependency, [commons-collections4](https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22commons-collections4%22), since the old one is for Java 1.3
