### ISSUE TITLE
The plugin tells me I have the latest support library, but it's not true :)

### ISSUE THREAD

**Issue by BoD** [ben-manes/gradle-versions-plugin#171]
Hi!
I'm using the Google maven repo, and this dependency:
`"com.android.support:support-fragment:26.0.0-beta2"`
and the plugin currently tells me:

```
The following dependencies are using the latest milestone version:
 - com.android.support:palette-v7:26.0.0-beta2
 - com.android.support:percent:26.0.0-beta2
 - com.android.support:support-annotations:26.0.0-beta2
 - com.android.support:support-fragment:26.0.0-beta2
```
(other dependencies omitted for brevity)

But the current latest version is actually `26.0.1`.

Not sure if this helps but this file exists: `https://dl.google.com/dl/android/maven2/com/android/support/support-fragment/maven-metadata.xml`

Also, attached is the full `--info` logs.
[logs.txt](https://github.com/ben-manes/gradle-versions-plugin/files/1225823/logs.txt)

**Comment by ben-manes** [comment]
Interesting. Usually this is because of a repository mismatch (e.g. hitting JCenter but the latest is in Maven Central), a bad metadata file, or a resolution strategy. Everything looks correct in your logs.

Can you try using `--refresh-dependencies`? That should force Gradle to query the repositories and not skip over based on its cache.

**Comment by BoD** [comment]
Using `--refresh-dependencies` produces the same results.

**Comment by vanniktech** [comment]
Probably `google()` wasn't added

**Comment by BoD** [comment]
Not sure what you mean by that @vanniktech.  I did add the Google repo to my `repositories` block if that's what you mean.

**Comment by ben-manes** [comment]
hmm, it worked for me.

```gradle
apply plugin: 'com.github.ben-manes.versions'
apply plugin: 'java'

buildscript {
  repositories {
    jcenter()
  }

  dependencies {
    classpath 'com.github.ben-manes:gradle-versions-plugin:0.15.0'
  }
}

repositories {
  google()
}

dependencies {
  compile 'com.android.support:support-fragment:26.0.0-beta2'
}
```

```
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes:gradle-versions-plugin:0.15.0

The following dependencies have later milestone versions:
 - com.android.support:support-fragment [26.0.0-beta2 -> 26.0.1]
```

**Comment by BoD** [comment]
Not sure if it's relevant but I also use other repos:
```
    repositories {
        mavenLocal()
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
```

FYI if you want to try to reproduce the issue, here is the repo:
https://github.com/BoD/CineToday
and please use the revision `90c2e9f4986a0073e60d3e10d7db7c0a2107f7f6`

**Comment by ben-manes** [comment]
Its odd. In your project it gives the wrong result but in the isolated it works fine...

**Comment by ben-manes** [comment]
oh, this is because of your resolution strategy forcing the version :)

**Comment by BoD** [comment]
Oh sorry about that :) Indeed!  When I comment this, it does work as expected!

Would you think it would still be possible that your plugin check if the latest version is used, even when using the resolution strategy?

**Comment by ben-manes** [comment]
We delegate to Gradle instead of rewriting its dependency management code. When we copy a configuration to muck with it, the resolution strategy is carried over. That can't be removed and some might want it honored. But if we use a detached configuration it would work, but there were repository bugs that made us switch over to a Configuration#copy instead.

You could check if the dependencyUpdates task is in the [execution graph](https://docs.gradle.org/current/javadoc/org/gradle/api/invocation/Gradle.html#getTaskGraph()) and disable the force.

**Comment by BoD** [comment]
Well I'm not sure I understood all that, but thanks a lot for your quick support, and congrats on the great plugin!  I think you can close this issue now.

**Comment by ben-manes** [comment]
Try adding `!gradle.taskGraph.hasTask(tasks.dependencyUpdates)` to your `resolutionStrategy` condition. It works for me by skipping your force if the task is going to be run.
