### ISSUE TITLE
intermediate updates

### ISSUE THREAD

**Issue by bagintz** [ben-manes/gradle-versions-plugin#189]
Is there a way with this tool to see if there are intermediate releases.  use case is when Google/Android releases new sdks (e.g. they just release sdk 27).  I would like to see if there is anything newer than my 26.* versions and not yet update to 27.

Thanks!

**Comment by ben-manes** [comment]
You could do this with a `resolutionStrategy` and a little scripting. The strategy could reject any major version greater than your current, thereby showing only minor/patch updates. Unfortunately, the `ComponentSelection` does not pass in your current dependency and you would need to look it up from the candidate's coordinate details. That might be done dynamically by querying Gradle and building a mapping dynamically, or by organizing your dependencies in a lookup format (e.g. a richer [dependencies.gradle](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle)).

There have been suggestions for breadcrumbs (#69, #95, #96). Due to how multiple resolution strategies can exist but are unordered and unaware of each other, I don't think we could use that. Similarly we might not be able to get the version metadata from an `ArtifactResolutionQuery`, which is likely to give the `pom` rather than `maven-metadata.xml`. That makes it hard for the plugin to do this automatically, since we prefer to use Gradle's resolution handling rather than reinvent it.

**Comment by bagintz** [comment]
@ben-manes I don't pretend to understand all of that, but I trust that it isn't a 'simple' solution.  Alternately, are there viewable web pages for each library, so if I had any questions I could just go look that up from the source to see the progression there?  I have not had success finding a single place to just type in a library to get information (like https://www.npmjs.com/ does for npm)

**Comment by ben-manes** [comment]
The vast majority of libraries are on Maven Central, where there is a handy [Chrome plugin](https://chrome.google.com/webstore/detail/maven-central-search/diihicfnoemjcdcakkgloofbpflofaal). Alternatively some are on JCenter which mirrors Central, so it might be easy to search instead. Those on custom repositories can only be handled programmatically. I just use Central.

**Comment by vanniktech** [comment]
I believe this is out of scope for this library. In 99% of the cases you're using the support library which will be bumped to `28.0.0` once the Android SDK `28` is out. If that's the case you know when to update.
