### ISSUE TITLE
Is there a nicer way of achieving build failure on versions out of date

### ISSUE THREAD

**Issue by westonal** [ben-manes/gradle-versions-plugin#192]
```
dependencyUpdates {
    outputFormatter = { result ->
        if (!result.outdated.dependencies.isEmpty()) {
            throw new GradleException('Abort, there are dependencies to update.')
        }
    }
}

bintrayUpload.dependsOn(dependencyUpdates)
```

So if I try to upload my package it fails if it's out of date.

But not loving how I am hooking into an output formatter, is there a nicer way?

**Comment by ben-manes** [comment]
Can you explain why you dislike this and a preferred alternative?

**Comment by westonal** [comment]
It doesn't read very nicely as it hooks onto `outputFormatter` but it has nothing to do with formatting an output, it's just the only place I saw I could test the output.

A more readable version might be:
```
dependencyUpdates {
    doOnReport { result ->
        if (!result.outdated.dependencies.isEmpty()) {
            throw new RuntimeException('Abort, there are dependencies to update.')
        }
    }
}
```

But an ideal, but less flexible version might be:

```
dependencyUpdates {
    failOnOutdatedDependencies = true
}
```

However, if what I already have is how you recommend I do it then 👍 I'm happy with that.

**Comment by ben-manes** [comment]
Yep, the name isn't perfect in this regard. An alias would be a nice addition.

@grv87 also asked for a failure assertion. Perhaps I was too quick to reject the idea. I am more inclined to recommend using the existing hook, though.

**Comment by westonal** [comment]
Oh yes, I see: #191

**Comment by grv87** [comment]
How could that hook work with standard output formatter, i.e. `outputFormatter = 'xml'`?

**Comment by ben-manes** [comment]
In that case, you would have to parse the output in a dependent task. It isn't elegant, but is not restrictive or difficult in Groovy.

If we added something like `doOnReport` that is run regardless of the formatter, that would be a more proper hook and likely what we should have implemented originally. That could internally be a list of closures that the call adds onto. Then, if we decided to offer some built in, it is merely appending to that list for execution rather than being a one-off. Since both of you are adamant that this is an important use-case and should be built in, I am more inclined to agree if its cleanly abstracted like the above.

**Comment by westonal** [comment]
> Since both of you are adamant that this is an important use-case and should be built in

I wouldn't put it that strongly, I'm happy that I can do it how I currently am, `doOnReport` would just be a bit nicer to read, but not worth doing on its own perhaps, however but the ability to have multiple closures on it might be useful for others.

For example, if they both want to output a custom xml and post a summary to slack, they would no longer need to do them both in the same closure.

But I'm imagining requirements here, mine are already covered, I just wondered if I was missing a better way.

**Comment by DemianTinkiel** [comment]
I also think this would be useful but rather than the original  @westonal 's  ideal scenario

> `dependencyUpdates {
    failOnOutdatedDependencies = true
}`

I'd prefer if I could do
`dependencyUpdates {
   onOutdatedDependencies = error
}`
or
`dependencyUpdates {
   onOutdatedDependencies = warn
}`
or the default
`dependencyUpdates {
   onOutdatedDependencies = none
}`

The 'doOnReport' is useful if you want to do more complex rules like max 5 etc

**Comment by ben-manes** [comment]
It sounds like `warn` would be a log statement whereas `error` is a build failure?

Running this task on every build isn't advised, because resolution is slow. By default Gradle will cache it for 24 hours, so it is faster on subsequent runs. But potentially it might not see a newer version until the cache expires. Failing the build makes sense if you are running this as a daily CI job (e.g. on jenkins) and don't want to bother parsing the report but instead push out an email with the console text when failed. So `error` makes sense to me, while `warn` less so.

**Comment by DemianTinkiel** [comment]
@ben-manes 

> It sounds like warn would be a log statement whereas error is a build failure?
> Failing the build makes sense if you are running this as a daily CI job (e.g. on jenkins) 

Yes you are correct, purpose is CI. The way I was thinking it is that if we had warning category we could also do something like max 5 warns before becoming error

>Running this task on every build isn't advised, because resolution is slow. By default Gradle will cache it for 24 hours, so it is faster on subsequent runs. But potentially it might not see a newer version until the cache expires.

isn't cache time controllable from CLI? if so perhaps slow resolution may not be an issue

**Comment by vanniktech** [comment]
The problem with `dependencyUpdates { onOutdatedDependencies = warn }` or any other approach like that would be that another use case could popup that would require some other configuration and then maybe `onOutdatedDependencies` becomes obsolete and is too simple.

Let's - for now - use the workaround with the `outputFormatter` hook and in the future once other things have been implemented get back to this if there's still need for it.
