### ISSUE TITLE
forced dependency resolution prevents dependencyUpdate lookup

### ISSUE THREAD

**Issue by tkruse** [ben-manes/gradle-versions-plugin#194]
Hi,

With an empty gradle project and the build.gradle file below, ```gradle dependencyUpdates``` will not show that a new version of commons-lang3 is availlable. This might not be a bug, but just a consequence of the force option. Might still be good to have some solution.

We did this because we wanted to use the same version of libraries across submodules of different types (gradle play framework plugin and java), and also for all transitive dependencies.

I could work on providing an example multi-module project with said 2 different kinds of modules to show our goal more clearly.

To reproduce (using gradle 4.3 myself):
```
buildscript {
    repositories {
        jcenter()
    }
}

plugins {
    // use with gradle dependencyUpdates, to check for updates
    id "com.github.ben-manes.versions" version "0.15.0"
}

apply plugin: 'java'

repositories {
    jcenter()
}

configurations.all {
    resolutionStrategy {
        force(
                "org.apache.commons:commons-lang3:3.5",
        )
    }
}

dependencies {
    compile("org.apache.commons:commons-lang3")
}
```

**Comment by tkruse** [comment]
Note that the following has no impact on dependencyUpdates:
```
dependencies {
  compile("org.apache.commons:commons-lang3:3.5") {force = true}
}
```

**Comment by ben-manes** [comment]
Yep, this is a consequence of using Gradle's APIs for resolution. Some may want their configurations honored, while others don't. If we resolve the metadata manually we reinvent their infrastructure and don't gain improvements, but can fast track our own. I think detatched configurations are immune to this, but we encountered bugs there too. There isn't enough control over resolution strategies to tune this, so we probably can't do much directly.

You can of course reduce the breadth of this, e.g. by not using `all`. Or you could observe the task graph and not apply some rules, e.g. `!gradle.taskGraph.hasTask(tasks.dependencyUpdates)`.

> compile("org.apache.commons:commons-lang3:3.5") {force = true}

I think that is because it is forced only for the `compile` configuration, but not all others. Since we copy the configuration and rewrite the dependencies to a dynamic query, it must lose the force on the update check. But, if you want to force other configurations then the above probably won't apply as globally as your original.

**Comment by tkruse** [comment]
thanks for the ideas. 
Not sure which configurations I could use instead of ```all```. Using "compile" reproduces the problem,  using something else I am not sure what will end up in my classpath. Note this also indicates that {force = true} works differently or at a different time.

Using gradle.taskGraph.hasTask(tasks.dependencyUpdates) will likely not work because the configurations closure is evaluated before the taskgraph construction, it seems
```
A problem occurred ...
> Task information is not available, as this task execution graph has not been populated.
```

This however seems to work, and can be part of our workaround:
```
if (!gradle.startParameter.taskNames.contains('dependencyUpdates')) {
```

You can close this ticket btw, as wontfix.

**Comment by ben-manes** [comment]
Unfortunately the only other option here is using a `componentSelection` rule to reject the candidate. When using `--info` it appears that `force` makes the metadata appear as the version, so it is very forceful in ensuring the version.

I guess the taskGraph trick worked in my testing when inside of a selection rule, e.g.
```gradle
configurations.all {
  resolutionStrategy {
    componentSelection {
      all { selection ->
        if (!gradle.taskGraph.hasTask(tasks.dependencyUpdates)) {
          force "org.apache.commons:commons-lang3:3.5"
        }
      }
    }
  }
}
```
But that is verbose and since no version is in your definition, it is resolved to `none`.

Sorry that its an edge case without any great workaround.
