### ISSUE TITLE
Newer version for transitive dependency not detected?

### ISSUE THREAD

**Issue by Riggs333** [ben-manes/gradle-versions-plugin#200]
When checking for dependency updates the transitive dependency (in my case Mockito) is not reported to have a newer version. (Using Gradle 4.4.1)

### build.gradle
```groovy
buildscript {
        ext {
                springBootVersion = '1.5.9.RELEASE'
        }
        repositories {
                mavenCentral()
        }
        dependencies {
                classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        }
}

plugins {
  id 'com.github.ben-manes.versions' version '0.17.0'
}

apply plugin: 'java'
apply plugin: 'org.springframework.boot'

sourceCompatibility = 1.8

repositories {
        mavenCentral()
}

// As spring-boot-starter-test ships with Mockito 1.10.19 we override the version here
// ext['mockito.version'] = '2.13.0'

dependencies {
        compile('org.springframework.boot:spring-boot-starter')
        testCompile('org.springframework.boot:spring-boot-starter-test')
}
```

### dependencyInsight

Running `gradle dependencyInsight --dependency mockito --configuration testCompile` results in
```
> Task :dependencyInsight 
org.mockito:mockito-core:1.10.19 (selected by rule)
\--- org.springframework.boot:spring-boot-starter-test:1.5.9.RELEASE
     \--- testCompile
```

### dependencyUpdates
Running `gradle dependencyUpdates` results in
```
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.17.0
 - org.springframework.boot:spring-boot-gradle-plugin:1.5.9.RELEASE
 - org.springframework.boot:spring-boot-starter:1.5.9.RELEASE
 - org.springframework.boot:spring-boot-starter-test:1.5.9.RELEASE

Generated report file build/dependencyUpdates/report.txt
```

The newer dependency org.mockito:mockito-core:**2.13.0** is available on maven central but not reported.

**Comment by ben-manes** [comment]
Transitive dependencies are not resolved and scanned for. They could be, but that would become a much larger graph and be slower to resolve. The first question is what does Maven's Version Plugin do? That was the gold standard that all subsequent build systems (Java and otherwise) were inspired by (directly or indirectly).

Traditionally it was considered a poor practice to rely on transitive dependencies, since the owner may refactor to remove it and break downstream code. At that time one would declare the dependency, even if in BOM style without the version, in order to explicitly communicate their intent. Since idioms change its okay to revisit this, but it would be helpful to know if anyone else follows your desired convention.

**Comment by sschuberth** [comment]
As usually updating the version of a transitive is out of your control, I don't see much sense in reporting it. Sure, you could e.g. tell Gradle to enforce a newer version of a transitive dependency, but then no one guarantees you that the dependency depending on the transitive dependency (Uh!) still works as expected.

If everybody just cared about their direct dependencies, the world would be a better place 😉

**Comment by ben-manes** [comment]
Its also worth looking how Netflix's nebula plugins faired in this regard. It sounds like the [gradle-dependency-lock-plugin](https://github.com/nebula-plugins/gradle-dependency-lock-plugin) tried to manage transitives in the same way as all other dependencies, but it was overly messy. Instead they now have [lock-experimental](https://github.com/nebula-plugins/lock-experimental) and delegate transitives to the [gradle-resolution-rules-plugin](https://github.com/nebula-plugins/gradle-resolution-rules-plugin).

In the Spring case I think they want you to upgrade with their version, unless you need to upgrade sooner due to bugs / features. That way they certify the entire package, supposedly following the approach that JEE application server vendors do. So it may be that they prefer you to delegate to them for non-critical dependency updates, like Mockito, and only take it upon yourself for a short period when absolutely necessary.

**Comment by Riggs333** [comment]
Thank you very much for your explanations and arguments! That makes sense to me. :+1: 
As you clarified why the gradle versions plugin behaves that way (works as specified) I'm fine with closing this issue.

For me I will then explicitly declare those transitive dependencies in my `build.gradle` if I want to (or have to) override the version. And it's ok to keep track of the updates for myself. :-)
