### ISSUE TITLE
Support for google() repository?

### ISSUE THREAD

**Issue by StephanSchuster** [ben-manes/gradle-versions-plugin#202]
I just stumpled upon this plugin. Great idea. However, it seems like it only checks jcenter() for updates. Most of my dependencies come from google() and are apparently not available in jcenter(). This makes this plugin completely useless for me. Can't you check all repositories listed in build.gradle. In my case - and probably many others - this would be:

`repositories {
        google()
        jcenter()
}`

Or did I miss something and this is already supported or technically not possible or desired?

**Comment by ben-manes** [comment]
It already does, but only uses the repositories associated with your configuration. If you include another, like `mavenCentral()`, it too will be queried. The plugin delegates to Gradle and does not add any default repositories itself. If you use `--info`, you will see a debug message of the repositories it is querying.

**Comment by StephanSchuster** [comment]
Strange. It was already querying google() and jcenter() but mostly only found dependencies with lower versions. How is that possible? Local cache?

When adding mavenCentral() your plugin delivers the expected output.

**Comment by ben-manes** [comment]
JCenter can be quirky by serving stale metadata for range queries but proxying to central for explicit versions. If an owner takes over their repository to see statistics, but keeps deploying to central, it gets out of sync.

Gradle’s plugin repository has been a pain by not being a real Maven repository until recently. I don’t know about Google’s, but wouldn’t be surprised if they did something different just because.

**Comment by StephanSchuster** [comment]
Alright, thanks for the clarification.
