### ISSUE TITLE
Feature request - Add dates

### ISSUE THREAD

**Issue by NickEcho** [ben-manes/gradle-versions-plugin#205]
It would be very useful for us if we can include the release date of dependencies in the output. 
This way we can fail the build if a library is X amount of days out of date.

**Comment by jaredsburrows** [comment]
This might be possible with the `maven-metadata.xml`: http://jcenter.bintray.com/com/github/ben-manes/gradle-versions-plugin/:maven-metadata.xml, since it has the `lastUpdated` in the XML.

```
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>com.jaredsburrows</groupId>
  <artifactId>gradle-spoon-plugin</artifactId>
  <version>1.3.0</version>
  <versioning>
    <latest>1.3.0</latest>
    <release>1.3.0</release>
    <versions>
      <version>1.0.0</version>
      <version>1.1.0</version>
      <version>1.2.0</version>
      <version>1.3.0</version>
    </versions>
    <lastUpdated>20171228150526</lastUpdated>
  </versioning>
</metadata>
```

**Comment by jaredsburrows** [comment]
Sorry, didn't mean to close!

**Comment by jaredsburrows** [comment]
The only concern I would say is that some libraries take a long time to update. I would focus on the feature diffs between versions and not the length of time between the updates.

**Comment by NickEcho** [comment]
Although I don't disagree with that but unfortunately sometimes our dependencies end up with some that are more then a year old. In this timeframe there could be numerous bug and security fixes we don't know of. 

To be a bit more clean on what I'm trying to do I'll try to describe what I exactly want:
- get the release date of the current used dependency
- get the release date of the *latest* version of dependency
- if the dates are N number of days throw an error.

Now I'm not sure if the 'lastUpdated' value is just the date of when the last version has been released or not. But if that's the case we are missing the release date of the current used dep and then I'm not sure if this is at all possible.

**Comment by ben-manes** [comment]
Central shows the file system‘s timestamp as the upload date. This is okay since they are an immutable, single repository. Unfortunately this date may differ when querying other repositories which may allow modifications. I don’t know if proxying repositories retain the original timestamp. Since this is inferred, it is not part of any standard metadata and not directly available in Gradle’s resolution. Likely direct repository calls would be needed to fetch the date, but we use Gradle’s apis instead or reinventing its dependency handling. So I am not sure if this ask is feasible.

**Comment by NickEcho** [comment]
Ah, that's a shame. Thanks for looking into it though!
