### ISSUE TITLE
Bug: Alpha versions are interpreted as release

### ISSUE THREAD

**Issue by MarcDahlem** [ben-manes/gradle-versions-plugin#206]
The release-dependency version for 'com.android.support.test.espresso.espresso-core' returns '3.0.2-alpha1'.
But it should definitely return '3.0.1'

**Comment by ben-manes** [comment]
The `revision` property refers to Gradle's resolution, which is derived from Apache Ivy's metadata. This does not map into Maven's world, which won the war for how dependencies are described in a Java repository. The Maven versioning scheme used `-SNAPSHOT` for non-releases and any other value is a release version. The usage of `alpha` and similar are custom that do not follow Maven's versioning rules, which adds more confusion. Some of this was available in Ivy, but you are querying a Maven repository and its artifacts should follow the conventions but do not. Unfortunately this is a common reality.

In the [maven-metadata](https://dl.google.com/dl/android/maven2/com/android/support/test/espresso/espresso-core/maven-metadata.xml), the `latest` and `release` flags are `3.0.2-alpha1`. Therefore the only way to filter these out is to add new resolution rules on top of the Maven standard. This is why Gradle later added `resolutionStrategy` and we then added support for it. If you define one to reject `alpha` (see `README` example) then the report will not include it in the suggestions.

**Comment by MarcDahlem** [comment]
Thanks for you fast answer.
I see now, how to solve the problem locally.

Is there a reason, why you didn't include the handling of such 'common' faults directly to the default config of the plugin?

**Comment by ben-manes** [comment]
1. The plugin was written for Gradle 1.0, so changing defaults between versions can be surprising.
2. The behavior matches Maven's version plugin, which was what everyone was used to at the time
3. The evolution of the default rules would probably grow since many dependencies use non-standard versioning. We added the features to ensure you won't be blocked (as much so as Gradle allows) rather than hard code filters or bypass Gradle's dependency logic.
4. It might be initially annoying by breaking your assumptions, but the fix is not too bad. The overall pain is not that high.
5. I had always hoped that Gradle would build this feature into a future release and perhaps help promote a set of conventions. (Then it wouldn't be my problem anymore 😉)
