### ISSUE TITLE
RFE: Option to only report on dependencies with updates

### ISSUE THREAD

**Issue by mmoayyed** [ben-manes/gradle-versions-plugin#217]
Proposal: the reporting facilities of the plugin should gain an extra option to only report back on dependencies that have later release versions.

**Comment by ben-manes** [comment]
Does setting a [custom output formatted](https://github.com/ben-manes/gradle-versions-plugin#custom-report-format) suffice? This or using the xml/json our intended for programmatic cases, like CI notifications.

**Comment by mmoayyed** [comment]
Thank you for your prompt reply. 

What you outline in terms of an output formatter is perfectly fine. I am wondering if the plugin can introduce a bit of "sugar" so that a simple boolean/enum type of flag might be well suited here as opposed to custom formatters. I would *imagine* that many would be interested in seeing a report of only dependencies with available updates in order to put together a task list and go about updating what it needs updating and so in that vein, it's possible that a simplified flag might find better use and adoption as opposed to folks writing custom formatters that more or less do the same, somewhat complicating the build and exposing them to what might become a breaking API later on, etc.

That said, if the formatter is the way to go, so be it.

Thanks again.

**Comment by ben-manes** [comment]
I originally included everything in order to easily debug and answer what the state of a given dependency was. I grouped them and put the updates at the bottom so that it would be usable, as I usually only looks at the bottom results for work items. In that case you could copy the section and start assigning tasks, etc.

When workflows get more complex, the alternative output formats were generously contributed. Then if you want to programmatically send a report, etc. its much cleaner than ad hoc text parsing.

I do think the text report could be a rabbit hole of customizations, which is why I've been hesitant to offer any. I am fine deferring to @jaredsburrows or @vanniktech as they might disagree with me.

**Comment by vanniktech** [comment]
Yes in general lots of people wants lots of different things. In the future we should have some way of tweaking the reports.

I guess we'd need to start collecting all of the requests that were made and decide which one we want to support and at the same time have some nice default values.

**Comment by ben-manes** [comment]
@jochenberger, do you recall why it works this way? Do you have an opinion on the proposed change?

**Comment by ben-manes** [comment]
We fixed that bug of the unexpected printing in the last release.
