### ISSUE TITLE
Unresolved dependencies appear to be configured incorrectly

### ISSUE THREAD

**Issue by alkamo** [ben-manes/gradle-versions-plugin#223]
In DependencyUpdatesReporter, buildUnresolvedDependency is called as follows:

```
buildUnresolvedDependency(dep.selector.name, dep.selector.group,
        currentVersions[keyOf(dep.selector)], message, latestVersions[keyOf(dep.selector)])
```
But, buildUnresolvedDependency is declared as:

```
 protected def buildUnresolvedDependency(String group, String name, String version,
                                          String reason, String projectUrl)
```

It looks to me like name is being assigned to group, group to name, and latest version to URL.

**Comment by ben-manes** [comment]
Feel free to fix that.

For some reason (name, group, version) was used instead of (group, name, version) per the standard coordinate conventions. When I fixed the sorting, I tried to change all of them to be consistent. But I might have made a mistake somewhere that didn't show up on the test samples. This is only on master so any bug caused by that change wasn't released.
