### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by vanniktech** [ben-manes/gradle-versions-plugin#228]
Can we also upload this plugin to maven central?

Bintray has been down in the past and it seems like it is down again today and `mavenCentral()` is much more reliable.

**Comment by jaredsburrows** [comment]
This is already on the Gradle Plugin repo. 

Use:
```
apply plugin: "com.github.ben-manes.versions"

buildscript {
  repositories {
    gradlePluginPortal()
  }

  dependencies {
    classpath "com.github.ben-manes:gradle-versions-plugin:$version"
  }
}
```

**Comment by ben-manes** [comment]
@jochenberger owns the bintray repository we're deploying to. Prior to JCenter, I had was using Central which has stricter rules. We decided not to use their mirroring since I'd have to give him my ssh key, and the plugin portal is on JCenter so this was where users would typically download from. So even without the ssh key issue, I'm not sure if it would be of much help. I'd expect large orgs to proxy the plugin repository, anyway.

**Comment by vanniktech** [comment]
Alright fair enough. Given that it's on the Gradle Plugin Portal too, I'll close.
