### ISSUE TITLE
Report return none version for BOM dependencies.

### ISSUE THREAD

**Issue by rosolko** [ben-manes/gradle-versions-plugin#231]
Related to [documentation](https://docs.gradle.org/4.6/release-notes.html#bom-import) configure build script:
```
dependencies {
    implementation("org.apache.logging.log4j:log4j-bom:2.11.0")
    implementation("org.apache.logging.log4j:log4j-api")
    testRuntimeOnly("org.apache.logging.log4j:log4j-core")
    testRuntimeOnly("org.apache.logging.log4j:log4j-jul")
    testRuntimeOnly("org.apache.logging.log4j:log4j-slf4j-impl")
}
```
By performing `dependencyUpdates` report show me:
```
The following dependencies are using the latest milestone version:
 - org.apache.logging.log4j:log4j-bom:2.11.0
 - org.apache.logging.log4j:log4j-api:none
 - org.apache.logging.log4j:log4j-core:none
 - org.apache.logging.log4j:log4j-jul:none
 - org.apache.logging.log4j:log4j-slf4j-impl:none

```

**Comment by ben-manes** [comment]
Our support matched Spring's BOM plugin and the semantics of the native support are different. For some reason there are file artifacts (e.g. local jar files) which should used to only exist for file dependencies. Since the following was determined by testing how the APIs behaved, another round would be needed to see what the subtle differences are to coerce to. I don't recall why we have to keep both `+` and `none`, but might be also due to Gradle's dependency management built on Ivy in very old versions.

https://github.com/ben-manes/gradle-versions-plugin/blob/88bcd3aa79c8f3455d6c33d91fe23b3230aeff30/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L132-L136

**Comment by rosolko** [comment]
@ben-manes Understood. So what decision will be? Close issue for now?

**Comment by ben-manes** [comment]
Not close, just needs to be investigated

**Comment by ben-manes** [comment]
I took a look into this and the problem appears to be an odd behavior of `Configuration#setTransitive(false)`. We set this prior to resolving a copy of the original configuration to avoid performing excess work, as you wouldn't want us to evaluate all of your transitive dependency versions being pulled in. That would make the task slower and not be helpful, since you might not know if bumping a transitive version is safe and not want to declare all of them.

The BOM's versions are considered transitive dependencies. Then when we resolve the configuration, it gives those as unresolved errors. That gets filtered through in the report as up-to-date since we can resolve the latest, so it coerces as up to date.

If we do not use `setTransitive(false)` then the versions show correctly in the report. Using the Gradle example in your link I get,
```
The following dependencies are using the latest milestone version:
 - dom4j:dom4j:1.6.1

The following dependencies exceed the version found at the milestone revision level:
 - com.github.ben-manes:gradle-versions-plugin [0.18.0-SNAPSHOT <- 0.17.0]
     https://github.com/ben-manes/gradle-versions-plugin

The following dependencies have later milestone versions:
 - com.google.code.gson:gson [2.8.2 -> 2.8.5]
     https://github.com/google/gson
 - org.springframework.boot:spring-boot-dependencies [1.5.8.RELEASE -> 2.0.2.RELEASE]
     https://projects.spring.io/spring-boot/#
```

I think the solution here will be to only disable transitive resolution if no dependencies are declared in the BOM-style. That way we don't incur the cost for everyone else, while resolving this issue for you.
