### ISSUE TITLE
Other repositories and latest version numbers

### ISSUE THREAD

**Issue by D-A-R** [ben-manes/gradle-versions-plugin#236]
It looks as though currently this is just looking for the highest version number (if I'm reading the [source](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy) correctly), which would seem logical

But I've ran into an issue that is fairly weird and wanted to get feedback, as it's causing a report of not having the latest version, when I believe I have

The following links show what I've ran into:
https://mvnrepository.com/artifact/org.jetbrains.spek/spek-junit-platform-engine
https://mvnrepository.com/artifact/org.jetbrains.spek/spek-api
https://mvnrepository.com/artifact/org.jetbrains.spek/spek-data-driven-extension

The platform engine and api both have other repositories with different versions in published by JetBrains and Spring Plugins, whereas the data drive extension only has the central repository. When doing a lookup I'm being told understandably that I need to go to 1.1.19 for the api and platform engine, however still 1.1.5 for the data driven extension. 

The dates would say that I should be on 1.1.5 for all, which testing it out seems to be correct. The dates would also verify this, although I will admit it all looks a bit strange

**Comment by ben-manes** [comment]
Usually the problem falls into either,
- The repository is not included. JCenter proxies point lookups to central, but not ranges and often had stale content. Make sure to include central and other repositories.
- The maven-metadata.xml is incorrect, e.g. due to being published by a partially compatible build tool. It looks fine on central.
- A resolution strategy is rejecting the candidate (logged at info)
- Gradle’s version comparator is incorrect.

My guess is the first one and JCenter is screwing up the range query. Make sure central is in your repository list too.

**Comment by D-A-R** [comment]
Ok so it is the maven.metadata.xml being incorrect

Spek have an issue raised against them to fix their versioning [170](https://github.com/spekframework/spek/issues/170)

If you look at the [maven-metadata](http://dl.bintray.com/jetbrains/spek/org/jetbrains/spek/spek-api/maven-metadata.xml) you can see it incorrectly has 1.1.19 as the latest

Off the back of this is there any way, or anything planned to allow an artifact or group to be excluded from version checking, other than the coding it into the componentSelection as a rule?

**Comment by ben-manes** [comment]
The selection rules are the hook into Gradle, so you can write one only for the update report rather than used elsewhere.

**Comment by D-A-R** [comment]
Ok. Do you think there's any scope in the future for adding the capability to supply a list of artifact or group names through config in Gradle and to have them excluded from being checked and the report output?

For example 
```
dependencyUpdates {
    exclude {
        artifacts = ["artifact1"]
        groups = ["group1", "group2"]
    }
}
```

There are many reasons for enabling this, as you may want to tie to a certain version of a dependency for very valid reasons for example. Or possibly get around issues like this

**Comment by ben-manes** [comment]
That would be a convenience to a resolution strategy behind the scene. So far I’ve only tried to maximize flexibility to not block users and haven’t spent much time on polish. I think this would be nice if we followed the dsl format of dependency exclude blocks rather than this slight variant. But the extra verbosity of the fully declared resolution strategy isn’t much more, so I don’t know whether you’d feel it was substantially better.

**Comment by D-A-R** [comment]
Fair enough, that makes sense. Looking at it to be honest I think the standard dependency exclude block syntax would be sufficient. What I proposed is an adjustment from convention and I don't feel it would provide enough benefit on review, so happy to go with convention

I'll close this issue as it's not relevant in itself. Thanks for your help!
