### ISSUE TITLE
Plugin can't resolve version for runtime dependency from BOM

### ISSUE THREAD

**Issue by rosolko** [ben-manes/gradle-versions-plugin#240]
Dependencies build script:

```
dependencies {
    implementation("org.apache.logging.log4j:log4j-bom:2.11.0")
    implementation("org.apache.logging.log4j:log4j-api")
    testRuntimeOnly("org.apache.logging.log4j:log4j-core")
    testRuntimeOnly("org.apache.logging.log4j:log4j-jul")
    testRuntimeOnly("org.apache.logging.log4j:log4j-slf4j-impl")
}
```

By performing `dependencyUpdates` report show me:

```
The following dependencies are using the latest milestone version:
 - org.apache.logging.log4j:log4j-api:2.11.0
 - org.apache.logging.log4j:log4j-bom:2.11.0
 - org.apache.logging.log4j:log4j-core:none
 - org.apache.logging.log4j:log4j-jul:none
 - org.apache.logging.log4j:log4j-slf4j-impl:none
```

Environment: Gradle 4.8
Plugin version: 0.19.0

_Note_: Moving dependencies from runtime to implementation scope made resolved version shown by plugin correctly.

**Comment by ben-manes** [comment]
We resolve a copy of each configuration and since the BOM isn't a dependency of `testRuntimeOnly` the versions don't bleed through. The `dependencies` task shows the bom as a dependency, even though querying through the configuration does not. So this seems to be a quirk with how BOMs were implemented internally. Sometimes `configuration.copy()` misses things. I don't know if there is anything we can do but investigate more, since we merely script the Gradle APIs.

If you add the BOM as a `testRuntimeOnly` dependency then it will show up as well. That's probably the desired fix for now.

**Comment by rosolko** [comment]
Got it. Thanks!
