### ISSUE TITLE
Add ability to inject our own gradle version checker

### ISSUE THREAD

**Issue by scphantm** [ben-manes/gradle-versions-plugin#246]
I work in a very large enterprise where out editions of gradle are custom packaged by us and distributed thru a folder structure in our artifactory system.  I love the idea of the gradle version checker, but i can't use it because we have a custom distribution

Is it possible for you to do a little refactoring, give me at trait or interface, that allows me to create my own gradle checker class and inject it into the plugin?

**Comment by ben-manes** [comment]
If you'd like to give it a try, a PR is welcome. See [GradleUpdateChecker#fetch](https://github.com/ben-manes/gradle-versions-plugin/blob/cc2d88d321cd3deb6a72baef6b5d12f5a2dc1fbc/src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy#L29-L44). You could probably extract out an interface for the fetch strategy, e.g. a function that accepts a `GradleReleaseChannel` and returns the `ReleaseStatus`. Since you wouldn't implement some channels, like nightly, it could return `Unavailable` in those cases.

@aaronols
