### ISSUE TITLE
Custom outputFormatter gives Project Dependency Updates twice

### ISSUE THREAD

**Issue by deepy** [ben-manes/gradle-versions-plugin#254]
I followed the example given and now I'm getting two Project Dependency Update printed, even when using --quiet.

build/dependencyUpdates/ is also empty.

My original goal however was to filter out some internal dependencies from the list, since simply rejecting the ComponentSelection still left them in the list.

**Comment by ben-manes** [comment]
Since we're not using Gradle's reporting infrastructure, I guess we don't honor `--quiet` like we should.

It was observed in https://github.com/ben-manes/gradle-versions-plugin/issues/217#issuecomment-379732368 that the `println` is always called regardless of the formatter. @jochenberger doesn't seem to be around anymore, unfortunately. I think removing it should be okay.

Also note that if you put the plugin on the root it will give an aggregated report, but if you put it on the subprojects you'll get one per.

**Comment by ben-manes** [comment]
Fixed by #281

**Comment by Blackbaud-JasonBodnar** [comment]
Question. Since the version number didn't bump (which is perfectly fine with such a small fix) how do I get my build to use the new code?

I tried:

`$ rm -Rf /home/jbodnar/.gradle/caches/modules-2/metadata-2.63/descriptors/com.github.ben-manes /home/jbodnar/.gradle/caches/modules-2/files-2.1/com.github.ben-manes
$ gradle --stop`

But it's still using the version without my fix.

**Comment by ben-manes** [comment]
You could try jitpack.io?

I’d like to fix #255 before we release, so we could do that soon.
