### ISSUE TITLE
Gradle kotlin-DSL : output to ./buildSrc/src/main/Libs.kt 

### ISSUE THREAD

**Issue by jmfayard** [ben-manes/gradle-versions-plugin#259]
Hello friends,

I'm currently to the gradle kotlin DSL

One super useful thing that it enables is centralizing the dependencies versions in one kotlin file and letting the IDE help you use it

```gradle
dependencies {
     compile Librairies.Ok<TAB> // will auto-complete to Libs.Okhttp
}
```

https://proandroiddev.com/gradle-dependency-management-with-kotlin-94eed4df9a28

The not fun part is to generate once for all that file with all the dependencies

So an idea I had is to hack your plugin to output a file like this one

```kt
// ./buildSrc/src/main/Libs.kt 
object Libs {

    /** https://github.com/square/okhttp     */
    const val Okhttp = "com.squareup.okhttp3:okhttp:3.11.0" // [up-to-date]
 
    /** https://github.com/ReactiveX/RxJava   */
    const val RxJava = "io.reactivex.rxjava2:rxjava:2.2.0"  // [ 2.2.2 ]
}
```

Does that sounds possible and any hints to help me?

**Comment by ben-manes** [comment]
I do the same thing in Groovy, with a [dependencies.gradle](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle) file. I keep the versions separate from the coordinates so that I can skim that section most of the time.

Your idea is probably most similar to the [gradle-libraries-plugin](https://github.com/fkorotkov/gradle-libraries-plugin). If a close match, maybe peeking at its code would help.

Gradle recently added [dependency locking](https://docs.gradle.org/4.8/userguide/dependency_locking.html) which could evolve to absorb this plugin's features. That also might be useful to see if you can work with, since its a built-in feature indicating where the Gradle team is heading.

**Comment by jmfayard** [comment]
Thanks a lot, very useful

**Comment by jmfayard** [comment]
@ben-manes I now have some working code! 

https://github.com/jmfayard/sample-synclibs

https://www.useloom.com/share/7defb57f3a85412e9e1a68f987e3d9b3

If you give it a try, would love to have some feedback

**Comment by jmfayard** [comment]
Thanks !
Sure, would be nice.
