### ISSUE TITLE
use-releases

### ISSUE THREAD

**Issue by sonOfRa** [ben-manes/gradle-versions-plugin#264]
The maven-versions-plugin has a task called ``use-releases`` https://www.mojohaus.org/versions-maven-plugin/use-releases-mojo.html

Which allows me to automatically updated dependencies like ``com.example.dependency:1.2.3-SNAPSHOT`` to ``com.example.dependency:1.2.3`` if it can find the proper non-snapshot version. Is there an equivalent task in this gradle plugin? It would be especially nice in combination with the gradle-release plugin.

We have in-house dependencies like C->B->A (and maybe D which also depends on B, so a kind of tree). While in development, B depends on the current snapshot version of A, and C on the snapshot of B. So when releasing the individual projects, we'd release A, then move B to depend on A instead of A-snapshot, release B, and repeating the same process for C.

After the release is done, we'd like to move everything back to *snapshots* that is, B should depend on A-next-SNAPSHOT, etc. Do you think this is feasible with this plugin?

**Comment by ben-manes** [comment]
Maven can do this because dependencies are defined in a singular format, whereas it varies a lot with Gradle. Gradle supports multiple syntaxes, build languages, and developers often externalize versions (but with different idioms). The flexibility makes this too hard to fully generalize, though you can find attempts like the [gradle-use-latest-versions](https://github.com/patrikerdes/gradle-use-latest-versions-plugin). I think you might be able to use something like that or perhaps rewrite your own versions file using our [custom reports](https://github.com/ben-manes/gradle-versions-plugin#custom-report-format) hook.

I think the versioning of projects with snapshots for internal repositories, a common practice in Maven, isn't a great fit for Gradle. Instead an incremental build with up-to-date checks across the repository, tends to be more productive. If you have fully switched from Maven you might decide to change your release process to be more Gradle-oriented with a mono-repo and no project snapshots.

**Comment by sonOfRa** [comment]
Multirepo sadly isn't an option currently, as our CI doesn't cooperate with that (we can only trigger full builds of everything on every push). But the other two suggestions look promising, I'll go see what I can do with those. Thank you!

**Comment by sonOfRa** [comment]
I built a shell script around the release process that does it for us now:

https://gist.github.com/sonOfRa/2f2940b3095733b39ef669dab9c78c8b

Leaving it here as it may be useful for others.
