### ISSUE TITLE
Simpler resolution strategy

### ISSUE THREAD

**Issue by binkley** [ben-manes/gradle-versions-plugin#287]
As a plugin user, I would like a simpler option for resolution strategy, so my configuration is easier for others to understand.

Currently:
```
    dependencyUpdates {
        resolutionStrategy {
            componentSelection { rules ->
                rules.all { ComponentSelection selection ->
                    boolean rejected = ['alpha', 'beta', 'rc', 'cr', 'm'].any { qualifier ->
                        selection.candidate.version ==~ /(?i).*[.-]${qualifier}[.\d-]*/
                    }
                    if (rejected) {
                        selection.reject('Release candidate')
                    }
                }
            }
        }
    }
```
However, I would like to say simply:
```
    dependencyUpdates {
        resolutionStrategy = 'release'
    }
```
or some similar, intuitive property from _within_ `build.gradle` (not a command-line flag).

**Comment by ben-manes** [comment]
The `revision` property can be set in the `build.gradle`, but it isn't very useful in practice. That is because Maven's published metadata is not very rich, and that the version naming rules are weak and often not followed. Gradle was originally built on Apache Ivy whose revisions are a little richer and all that we had access to control.

The resolutionStrategy is Gradle's syntax which is verbose but powerful. This means you can work around even the most confusing cases, e.g. some use even/odd versions to denote beta vs release. Since there isn't a strict set of rules around versioning, we can't in good faith dictate what `release` means. At best we could provide a little convenience to shrink a few lines of code in your sample, which is easy enough to hide in an external script. Unfortunately this doesn't help much because someday a dependency will break this convenience for you and you'll have to customize the strategy, which forces you back to using the verbose syntax.

**Comment by binkley** [comment]
@ben-manes Thanks for the explanation.  Is there an elegant way to hide that configuration blob away elsewhere?  I have other devs on the team complaining, which is both reasonable and unreasonable.

**Comment by ben-manes** [comment]
Do you split your build into multiple `.gradle` files? If so then it’s easy to stash away from the important build logic.

**Comment by binkley** [comment]
@ben-manes That's a good suggestion; I'll give it a go.  Thanks for the chat.  I'm good for closing this issue.

**Comment by ben-manes** [comment]
great, glad I could help
