### ISSUE TITLE
How to get current version  in resolutionStrategy`?

### ISSUE THREAD

**Issue by jcornaz** [ben-manes/gradle-versions-plugin#313]
When writing a resolutionStrategy how can I know what is the current used verision?

Optimally I would like to be able to write something like this:

```kotlin
resolutionStrategy {
  componentSelection {
	all {

	  // For simplicity sakes I consider that the presence of '-' in version number denotes an unstable version (like 1.0-alpha, 1.2.3-rc.1, etc.)
	  val isCurrentVersionStable = '-' !in currentVersion
	  val isCandidateStable = '-' !in candidate.version

	  if (isCurrentVersionStable && !isCandidateStable) {
		reject("Version less stable than the one currently used")
	  }
	}
  }
}
```

Basically, I want to get a proposition to upgrade from `1.0.0-beta.2` to `1.0.0-rc.1`, but I don't want to be proposed to upgrade from `1.2.3` to `2.0.0-alpha.1`

How could I write such kind of strategy?

**Comment by ben-manes** [comment]
Unfortunately that isn’t exposed as part of Gradle’s api. You would need to
maintain a manifest to look up into, as the callback doesn’t provide those
details. I don’t think there’s much we could provide to help.

**Comment by jcornaz** [comment]
Thanks for your answer.

But how does the plugin know that there is a new version and how does it print the current version in the console then?

**Comment by ben-manes** [comment]
The plugin is actually quite simple and lets Gradle do the actual work.
1) Iterates over all projects
2) Iterates over all configurations in the project
3) Resolves the configuration's dependencies with your version
4) Resolves a copy of the configuration with the dependency versions set to `+`
5) Generates a report of the differences

This way you might declare `a:b:1.2` and `x:y:2.3.+`, where the latter resolves to `2.3.1`. When the latest version runs, it then finds `a:b:2.0` and `x:y:2.4.0`. By matching on the group/name and using Gradle's version comparator, we can print the findings.

At best we might be able to maintain a task-level property that you could query against and reset before the latest configuration is resolved. That's a global property, which would be problematic if Gradle adds parallel dependency resolution. The resetting is needed because a multi-project build might have a dependency declared in two different sub-projects at different versions, so report has to note both resolutions.

That means it might be best for the user to maintain a central manifest, e.g. `dependencies.gradle`. That's popular already, e.g. to state `compile libraries.caffeine`. Then you could query your manifest to find out if you have an explicit version of that coordinate with a pre-release string.

**Comment by jcornaz** [comment]
> 3. Resolves the configuration's dependencies with your version

How does this step work? Is it possible to somehow retrieve its result? Dumping it to a file or whatever?.

>At best we might be able to maintain a task-level property that you could query against and reset before the latest configuration is resolved. That's a global property, which would be problematic if Gradle adds parallel dependency resolution. The resetting is needed because a multi-project build might have a dependency declared in two different sub-projects at different versions, so the report has to note both resolutions.

Why does it have to be global? Cannot it be at the project level?

>That means it might be best for the user to maintain a central manifest

Can these manifests be generated? (I intentionally make it plural, because there has to be one per project, to support *dependency declared in two different sub-projects at different versions*.

**Comment by ben-manes** [comment]
> How does this step work? Is it possible to somehow retrieve its result? Dumping it to a file or whatever?

This calls Gradle's api to request a [resolved configuration](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/Configuration.html#getResolvedConfiguration--). This could be dumped to a file or elsewhere, but that requires looking up somehow.

> Why does it have to be global? Cannot it be at the project level?

It is a global variable, which could be task level. However the scope of interest is a configuration, which a project contains many of, and could be processed in parallel. The resolution strategy is attached to a configuration and its closures are not given the configuration being executed upon. Therefore we cannot simply provide a `Map<Configuration, Map<Dependency, Version>>` to query into, because the component selector does not know which configuration it is running for. We are limited by the [Gradle API](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ComponentSelectionRules.html).

> Can these manifests be generated?

Yes, one per configuration. For example, the new dependency locking feature is a [per-configuration file](https://docs.gradle.org/current/userguide/dependency_locking.html#lock_state_location_and_format) that outputs the current versions, to disallow versions to be modified without regenerating a new lock file.

From the APIs, the only way that I know how to provide the context is through a thread-scoped variable, e.g. a `ThreadLocal` or a task output property. However, that assumes no configuration-level concurrency by Gradle and disallows us leveraging it in the future. This should be doable today using the Gradle Worker API, for example.

The only [workable solution](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L168-L172) that I see is to use a custom interface or enrich only the `dependencyUpdates.resolutionStrategy`, to pass in that manifest details in the closure supplied to `Configuration.resolutionStrategy(closure)`. As the callback itself is single-threaded and the manifest supplied, it could perform the setup/teardown necessary. Ideally this would be a resolutionStrategy, and while it would satisfy the constraints, it would be unnatural to bypass Gradle's APIs for a task's with a custom life-cycle. The custom interface would avoid that problem, but then be unnatural by deviating from Gradle's dependency handling.

You are welcome to experiment and hack at the plugin to see if you can find a nice solution.

**Comment by ben-manes** [comment]
@ghus-raba contributed a really nice solution to this problem, so closing. We should look into making another release soon with the improvement.
