### ISSUE TITLE
Would you consider accepting a PR for "gradle.properties reporter"?

### ISSUE THREAD

**Issue by vlsi** [ben-manes/gradle-versions-plugin#341]
That is a reporter that generates/updates version in `$rootDir/gradle.properties` file.

I know there's https://github.com/jmfayard/buildSrcVersions, however it looks too much for me.

**Comment by jmfayard** [comment]
Yes, see https://github.com/ben-manes/gradle-versions-plugin/issues/323

**Comment by jmfayard** [comment]
Oh you mean adding a new plug-in or contributing a part of my plug-in upstream? In both cases, no problem for me.

**Comment by ben-manes** [comment]
You could get pretty far using a custom [outputFormatter](https://github.com/ben-manes/gradle-versions-plugin#custom-report-format). Some of the other plugins might also be useful, e.g. `gradle-libraries-plugin`, [line scripts](https://github.com/line/gradle-scripts#dependency-management), depending on your preferences. We'd be happy to list other integrations if you want to write a new plugin.

I don't think we should be promoting an approach towards how users manage their dependencies.

However my bias towards minimal scope creep is also because I've scratched my itch and am not very active. I am happy to provide commit access to those interested in driving this plugin forward and trust the decisions to more active maintainers.

**Comment by vlsi** [comment]
>I don't think we should be promoting an approach towards how users manage their dependencies.

That basically nails the answer. I see, thanks.
