### ISSUE TITLE
The following dependencies exceed the version found at the milestone revision level

### ISSUE THREAD

**Issue by memelet** [ben-manes/gradle-versions-plugin#355]
I know this was reported before and the response was to use --refresh-dependencies. But I'm seeing this over and over across branches. In one branch DU says to update the dependency. In the other it says I'm too far ahead.

I can always fix it by using --refresh-dependencies, but that takes a long time.

I don't know yet how to make this reproducible. But any insight into what might be happening would be helpful.

**Comment by ben-manes** [comment]
Since we script Gradle's dependency management, its owned by their caching. That is configurable, most likely via [ResolutionStrategy.cacheDynamicVersionsFor](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html). You could probably set this on the `dependencyUpdates` resolution strategy rather than globally. I suspect if you set this to 0 seconds then it would re-resolve each time, just like `--refresh-dependencies` forces.

**Comment by memelet** [comment]
But `--refresh-dependencies` fully re-downloads everything, which takes a long time. I'll close this for now until I can produce something actionable. Thanks again.
