### ISSUE TITLE
not able to check release version always show milestone and release-candidate

### ISSUE THREAD

**Issue by lfarkas** [ben-manes/gradle-versions-plugin#374]
even if i run with:
`./gradlew dependencyUpdates -Drevision=release`
it shows like these:
```
- org.hibernate:hibernate-c3p0 [5.4.10.Final -> 6.0.0.Alpha4]
     http://hibernate.org/orm

gradle release-candidate updates:
 - Gradle: [6.1.1 -> 6.2-rc-1]
```

anyway it'd be good to be able to set this properties in the build.gradle not just only in the command line.

**Comment by ben-manes** [comment]
Please use a resolution strategy (see https://github.com/ben-manes/gradle-versions-plugin#revisions).

The `revision` flag is an Ivy concept that doesn't map into the Maven world. It only makes sense for internal Ivy repositories. This plugin was originally written against Gradle 1.x, when Gradle built on top of Apache Ivy for all of its dependency management. A much later version replaced most of Ivy and provided resolution strategies for a more configuration. You can ignore `revision` as a legacy feature.

**Comment by lfarkas** [comment]
what does it means? imho it would be useful to set some kind of property in order to check only latest release version.

**Comment by ben-manes** [comment]
Maven considers any version without -SNAPSHOT to be a release version. The qualifiers do not follow their versioning format and so they just try to sort in a nicer manner for what latest means. This means we cannot apply a rule because many projects use non-Maven custom formats. This is why a resolutionStrategy that you define is required instead.

Apache Ivy does define rules but that is for ivy.xml files and not pom.xml which became the standard. Using an Ivy flag won’t help against a Maven repository.
