### ISSUE TITLE
Change gradleReleaseChannel default to "current"

### ISSUE THREAD

**Issue by ianbrandt** [ben-manes/gradle-versions-plugin#387]
Greetings,

Thank you for this very helpful plugin.

The default release channel for most update managers I'm familiar with is _stable_, and for the sake of build stability I would think that's the default channel most would want for their Gradle version in practice.

In the spirit of convention over configuration, it would be nice to not have to configure the Gradle Versions Plugin to use the `"current"` release channel in the majority of my builds.  Would you accept a PR that changes the default `gradleReleaseChannel` from `"release-candidate"` to `"current"`?

**Comment by ben-manes** [comment]
I think everyone would have different preferences here, unfortunately.

1. Since the Maven version format only has released and snapshot, many dependencies use a non-standard format. That requires then using a custom resolution strategy since the report will show these betas. That has the same problem you see here, where you would have to configure to your preference report.
2. Gradle versions often include breaking, incompatible changes in minor versions. They rely on users running RCs and finding issues before it goes live. It is in your interest to be aware of these, even if you only use the stable version.
3. The Gradle release channel has a nice breadcrumb feature showing the latest stable and latest release candidate, e.g.
```
Gradle release-candidate updates:
 - Gradle: [6.1.1 -> 6.2.2 -> 6.3-rc-4]
```
3. If you have many different builds, you will probably want to have shared configuration anyway. There are many approaches which should mitigate your main concern.

My inclination would be leave as is. The json format is useful if you want to add automation, e.g. an email report, which could easily ignore these cases as the format includes the necessary details.

**Comment by ianbrandt** [comment]
Understood.  Thanks for considering it.  I hadn't noticed the breadcrumb feature, likely just due to timing.  That does lessen the use case.

**Comment by BernhardPosselt** [comment]
Could you at least output both versions then? Not everyone wants to play beta tester for gradle.

**Comment by ben-manes** [comment]
We do output both, if any updates are available, as described above using breadcrumbs. Since we don't update your build it is up to you to decide on using a pre-release version.
