### ISSUE TITLE
want to contribute an html report; getting 403

### ISSUE THREAD

**Issue by jcrokicki** [ben-manes/gradle-versions-plugin#417]
Hi Ben (and others) - I created a basic html report generator that mimics the test report generator, but when i try to push the branch I created from master, I get a 403. What am I doing wrong?  I believe the credentials are correct.

C:\src\git-3rdparty\gradle-versions-plugin>git push --set-upstream origin html-report
remote: Permission to ben-manes/gradle-versions-plugin.git denied to jcrokicki.
fatal: unable to access 'https://github.com/ben-manes/gradle-versions-plugin.git/': The requested URL returned error: 403

thanks!
- john

**Comment by ben-manes** [comment]
Hi John,

This is because you are pushing directly to this repository, where you do not have commit access. When you cloned the repository, the `.git/config` origin is set to ours. If you fork the repository, a copy will be placed under your github account. You can click the fork button and then modify your config's origin to the new location, push, and send a PR.

Once a user has offered a modestly sized PR and code review then I typically grant then access to commit directly, in the hopes that they might be interested in making future contributions.

For the html report, I hope you noticed the [outputFormatter](https://github.com/ben-manes/gradle-versions-plugin#custom-report-format) which has been our escape hatch so far to support richer, custom formats.

**Comment by jcrokicki** [comment]
Fair enough. I will do that today.
Yes, I saw the outputFormatter approach.  Having dozens of Jenkins jobs would require adding that code in many places, causing a lot of code duplication and maintenance.  I'm hoping the simple approach I've taken will be looked upon with favor :-)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/29876287/92150216-15620980-eded-11ea-9f7b-8f1872fffcc5.png)

Thanks!
- john
