### ISSUE TITLE
outputFormatter = "plain, html" does not work correctly

### ISSUE THREAD

**Issue by bekuno** [ben-manes/gradle-versions-plugin#419]
I tried the new outputFormatter "html" in the form
`outputFormatter = "plain, html"`
It gave two output lines:
~~~
Generated report file C:\Users\xx\StudioProjects\xxx\build\dependencyUpdates\report.txt
Generated report file C:\Users\xx\StudioProjects\xxx\build\dependencyUpdates\report.txt
~~~
but no html report.
But with `outputFormatter = "html, plain"`
the result is fine:
~~~
Generated report file C:\Users\xx\StudioProjects\xxx\build\dependencyUpdates\report.html
Generated report file C:\Users\xx\StudioProjects\xxx\build\dependencyUpdates\report.txt
~~~

**Comment by ben-manes** [comment]
This looks like it is because when splitting the string the option isn't trimmed. The default is plain text, regardless of what the value is. So the first case is ["plain", " html"] which falls through to the default clause.

https://github.com/ben-manes/gradle-versions-plugin/blob/ce34c2196ccd08c45d5e69780dc6760d8fa42e4e/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy#L97-L99

https://github.com/ben-manes/gradle-versions-plugin/blob/ce34c2196ccd08c45d5e69780dc6760d8fa42e4e/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy#L124-L142

**Comment by ben-manes** [comment]
Thanks @jcrokicki!
