### ISSUE TITLE
html output - Later dependencies - Latest Version shows the Current Version

### ISSUE THREAD

**Issue by bekuno** [ben-manes/gradle-versions-plugin#420]
Output plain:
~~~
The following dependencies have later release versions:
 - com.android.tools.build:gradle [4.0.1 -> 4.2.0-alpha09]
 - com.asamm:locus-api-android [0.3.17 -> 0.9.15]
     https://github.com/asamm/locus-api-android
 - com.getkeepsafe.dexcount:dexcount-gradle-plugin [1.0.3 -> 2.0.0-RC1]
~~~

Output html:
![grafik](https://user-images.githubusercontent.com/32555742/92336601-aa415d00-f0a2-11ea-8d06-dc2d1ad7e2ce.png)

**Comment by ben-manes** [comment]
A quick glance, and are you using revision=release? That seems to be using the current instead of the available version.

https://github.com/ben-manes/gradle-versions-plugin/blob/ce34c2196ccd08c45d5e69780dc6760d8fa42e4e/src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy#L202-L211

**Comment by bekuno** [comment]
Yes, `revision = "release"`.

**Comment by jcrokicki** [comment]
> Yes, `revision = "release"`.

Could you please provide the entire command line so I know that I am reproducing your issue properly?
thanks!
-john

**Comment by jcrokicki** [comment]
My bad... getVersion() vs. getAvailable.getRelease(). Will be fixed soon.
