### ISSUE TITLE
release revision should filter Apache Milestone release by defeault

### ISSUE THREAD

**Issue by hebra** [ben-manes/gradle-versions-plugin#425]
Unfortunately Apache projects usually promote milestone releases into the releases channel instead of snapshots on Maven Central (or similar). Milestone releases are indicated by the suffix `-Mn` where `n` is the milestone as part of the version number. 
Example: `2.0.0-M24`

As these milestones can not be seen as stable releases the default behaviour for the plugin should be to not recommend these versions as newer than the current stable version.

## Steps to repeat

1. In `build.gradle` file set the revision handler to `release`
`dependencyUpdates.revision="release"`

2. Add a Apache-related dependency, e.g. directory server

```
dependencies {
    implementation "org.apache.directory.server:apacheds-core:1.5.6"
}
```

3. Run the dependencyUpdates task will suggest the following
```
 - org.apache.directory.server:apacheds-protocol-ldap [1.5.6 -> 2.0.0-M24]
```

## Issue
Instead of `2.0.0-M24` the suggested version to should `1.5.7` (currently the latest stable)

**Comment by ben-manes** [comment]
We use Gradle's version comparator, which is defined there as [StaticVersionComparator](https://github.com/gradle/gradle/blob/master/subprojects/dependency-management/src/main/java/org/gradle/api/internal/artifacts/ivyservice/ivyresolve/strategy/StaticVersionComparator.java). In the past they have been open to changes, so you should try opening an issue with them. If adopted then it will automatically show up here since we defer to Gradle for the resolution.

**Comment by ben-manes** [comment]
For clarity, `revision` is defined by Apache Ivy which Gradle original used and later fork (and this plugin written when that was our only option). Since Maven lacks richer concepts, it means a `integration` goes to `-SNAPSHOT` and `release` goes to any other version. The best mechanism is to use a `resolutionStrategy` to define your own filtering rules.
