### ISSUE TITLE
Google cloud storage maven projects

### ISSUE THREAD

**Issue by NikkyAI** [ben-manes/gradle-versions-plugin#436]
adding repositories hosted on google cloud storage like this is rather popular in organisations

```gradle-kts
maven("gcs://mvn-bucket/releases") {
	name = "$organization maven"
}
```

**Additional context**

not sure how gradle does it but..
you need to have `gcloud` installed on the system
and the env var `GOOGLE_APPLICATION_CREDENTIALS` pointing to a json file containing the service account
see: https://cloud.google.com/docs/authentication/getting-started

seems like google directly provides a sdk: `com.google.cloud:google-cloud-storage:`
and it seems easy to use, this seems to be the only code necessary to read and ~~write~~ files from gcs 
https://github.com/tehlers/gradle-gcs-build-cache/blob/master/src/main/kotlin/net/idlestate/gradle/caching/GCSBuildCacheService.kt

**Comment by NikkyAI** [comment]
refreshVersions still had outdated contributing guidelines forwarding to this as its parent project.. but apparently it does not rely on it anymore, this probably works here nayways

**Comment by ben-manes** [comment]
This should work here because we let Gradle resolve as normal, so any built in dependency management feature works out of the box.

That project rewrote to its own, more limited, NIH resolution which has many failure modes. Hopefully they can evolve it to cover all cases and stay up to date with Gradle’s internal logic.
