### ISSUE TITLE
Cannot determine latest version for kotlin-stdlib on plugin version 0.32.0+

### ISSUE THREAD

**Issue by davidburstromspotify** [ben-manes/gradle-versions-plugin#443]
Using `com.github.ben-manes.versions` version 0.35.0 and Gradle 6.7:

```txt
Failed to determine the latest version for the following dependencies (use --info for details):
 - org.jetbrains.kotlin:kotlin-stdlib
     1.4.20-RC
The exception that is the cause of unresolved state: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.jetbrains.kotlin:kotlin-stdlib:.
Required by:
    project :project
```

This is a regression from 0.31.0, which correctly determines the latest milestone version.

The build script in question uses
```kotlin
dependencies {
  api(platform(project(":platform")))
  implementation(kotlin("stdlib"))
}
```
and the `:platform` module defines
```kotlin
dependencies {
  constraints {
    api(kotlin("stdlib"), "1.4.20-RC")
  }
}

**Comment by ben-manes** [comment]
Can you provide a sample project to debug from? We might need to broaden the [stdlib workaround](https://github.com/ben-manes/gradle-versions-plugin/blob/6c4a1e89c8d961313fa4d3c2a37283680b4e8997/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L134-L139) based on your project setup.

Kotlin is a bad citizen wrt how it hacks at Gradle to be incompatible with the standard APIs. This leads to us having to reverse engineer their ad hoc, hard coded behavior so that Gradle can resolve generically. I don't know why they are not following standard idioms and expect others to fix their messes, but it is frustrating.

**Comment by davidburstromspotify** [comment]
I believe this project should reproduce the issue nicely: [gradle-versions-plugin-issue-443.zip](https://github.com/ben-manes/gradle-versions-plugin/files/5507239/gradle-versions-plugin-issue-443.zip)

**Comment by ben-manes** [comment]
It seems to have included a version that is `null` as the source dependency, causing a resolution failure. Filtering that out did the trick and not a problem for prior kotlin projects bug fixed against.

```
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes:gradle-versions-plugin:0.36.0

The following dependencies have later milestone versions:
 - org.jetbrains.kotlin:kotlin-stdlib [1.4.10 -> 1.4.20-RC]
     https://kotlinlang.org/

Gradle release-candidate updates:
 - Gradle: [6.7: UP-TO-DATE]
```

**Comment by davidburstromspotify** [comment]
Cool, thank you for resolving the issue so fast!
