### ISSUE TITLE
Move dependencyUpdates to build/reports/

### ISSUE THREAD

**Issue by jaredsburrows** [ben-manes/gradle-versions-plugin#455]
Can we move the `dependencyUpdates` folder that is created under `build/` to the `build/reports/` folder?

**Comment by ben-manes** [comment]
Yes and no...

It might be too late because it would be a silent breaking change and many users appear to have CI integration scripts. So I think the default has to remain unchanged for now.

You can specify [outputDir](https://github.com/ben-manes/gradle-versions-plugin/blob/8abcaae363e4bb187ad7c113da56c2184431e7d2/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy#L46) to configure it locally. wdyt?

**Comment by jaredsburrows** [comment]
Make sense!

```
tasks.named("dependencyUpdates").configure {
  outputDir = ...
}
```
