### ISSUE TITLE
Report Misses Dependencies because of Unchecked Configurations

### ISSUE THREAD

**Issue by mroeppis** [ben-manes/gradle-versions-plugin#507]
I'm missing dependencies when checking the report. When debugging the plugin using an included build I discovered that the configurations holding the missing dependencies are being skipped because they are not classified "useful":

https://github.com/ben-manes/gradle-versions-plugin/blob/6f7b95d52cbbaa9023384b9c6fb84c54937f712a/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy#L70-L78

When running the above code with `resolve(...)` for all configs more dependencies are reported.

Since the reason behind the `isUsefulConfiguration` flag is not self-explanatory it would be nice to know why it's necessary. However, there should be another way to manage this.

I also found out that `Failed to resolve ...` error messages may occur because some constraints inside selected configurations can't be copied. It happens when trying to copy the configuration itself:

https://github.com/ben-manes/gradle-versions-plugin/blob/6f7b95d52cbbaa9023384b9c6fb84c54937f712a/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L273

Since this is a Gradle issue I [raised](https://github.com/gradle/gradle/issues/17179) one on their end.

---
I use the latest plugin version `0.38.0` running with Gradle `6.7.1`

**Comment by ben-manes** [comment]
I believe the problem that we had is the whole `canBeResolved` and `canBeConsumed` mess when Gradle changed configurations to not be resolvable. However that isn't properly set and, if I recall correctly, some backdoors allow some to bypass it. As this only applied to later versions Gradle, it was also a compatibility pain.

I am fine if we can refine this or somehow to it correctly. You can see the discussion in https://github.com/ben-manes/gradle-versions-plugin/pull/378 and the linked issues.

**Comment by mroeppis** [comment]
What would happen if `isUsefulConfiguration` was removed? Is this a Kotlin issue? If so, it might be necessary for some people to restrict configurations as is done right now. On the other hand it would only be fair to allow more configurations to be checked if wanted by a user.

Could we define an input closure allowing to configure configurations?

**Comment by ben-manes** [comment]
By removing we would try to resolve configurations which are not allowed for dependency resolution. Prior versions of Gradle allowed all to be resolved, so we iterated over all of them to generate the report. If you try removing now, you'll observe a lot of errors when Gradle rejects resolution. It might be that we should try to resolve, catch the error, and suppress it. I find the [documentation](https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs) on this concept very confusing and it seems to be ad hoc in usages by Kotlin & Android, and that `Configuration.copy` sometimes misses necessary metadata so it fails weirdly.

Since the failure is an immediate throwing of an exception, I kind of think the best is just to try and log.info that we skipped it. That way we get the most accuracy and don't try to detect on whatever the metadata claims. That should be fast and maybe least error prone. What do you think?

**Comment by mroeppis** [comment]
Potential errors shouldn't bother us. That's why we've got tests.
My intent was not to disadvantage somebody. After all you and the other contributors from #378 made a joint decision, I guess. And yes, maybe there are users saying: "Trying to resolve that doesn't make sense at all. So why?".

I have nothing against your suggestion. It's more like the opposite, i.e. I'd actually prefer it. Speaking of my projects I don't see the point in skipping a configuration. I also like your idea because it would take only a minimal change to make it happen. We could start by reverting the change to sources from [1c6627e](https://github.com/ben-manes/gradle-versions-plugin/pull/378/commits/1c6627ecc8d6f49ab89d5b7e73770ee9a9b03799).

Are you fine with changing the log level right here?

https://github.com/ben-manes/gradle-versions-plugin/blob/9bef5cb55bee63f2e51b3456c1172102cf4fb593/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy#L83-L91

Maybe we should also change the wording to what you wrote. Like `Skipping configuration x:y because ...`

**Comment by ben-manes** [comment]
Yep, I'm fine with the log level being changed and using your new message format.

**Comment by mroeppis** [comment]
Closing since agreed changes have already been merged (see #522).
