### ISSUE TITLE
Feature Request: dependencyUpdates Task Should Accept Version Rules File

### ISSUE THREAD

**Issue by mroeppis** [ben-manes/gradle-versions-plugin#510]
The `rejectVersionIf{ ...}` closure comes in handy when you need to make candidate version excludes. Once the number of excludes grows significantly (i.e. you need to scroll to read everything) it feels rather inconvenient to place such an extensive construct inside a buildscript.

Referring to the plugin's role model, the **Versions Maven Plugin**, a [version rules file](https://www.mojohaus.org/versions-maven-plugin/version-rules.html) would add the ability to unite explicit coordinate excludes combined with regex pattern matching in one dedicated place. Such a file would make a complex logic with global and dependency-based excludes easier to read as well.

The following approach could be used:
* add an optional input file for the version rules to the plugin task
* use this file to instantiate a custom type of `ComponentFilter`
* pass the type instance to `rejectVersionIf{ ...}`

**Comment by ben-manes** [comment]
I think once a build outgrows `rejectVersionIf` then a `resolutionStrategy` should be used. Gradle 7.0 includes support for [version catalogs](https://docs.gradle.org/7.0/userguide/platforms.html#sub:version-catalog-declaration), e.g. externally via [libs.versions.toml](https://docs.gradle.org/7.0/userguide/platforms.html#sec:sharing-catalogs). I think the desired expectation would be that you could use native support to force the version to those defined in your `toml` file, and this would not require any plugin support as out-of-the-box Gradle behavior.

**Comment by mroeppis** [comment]
@ben-manes : Are you saying this mechanism could be used to narrow down candidate version suggestions when resolving the latest dependencies with your plugin? If so, I have seen only [explicit excludes](https://docs.gradle.org/7.0/userguide/rich_versions.html#sec:rejected-version) so far, but no pattern matching. What's more, only users of Gradle 7.0 or later could benefit from it.

**Comment by ben-manes** [comment]
We support a custom `resolutionStrategy` which narrows down versions. The `rejectVersionIf` is merely a convenience call that creates this, since the DSL is a little verbose for simple use-cases. In our enhanced resolution strategy, we provide the `currentVersion` in addition to the `candidate`. We apply this resolution strategy and let Gradle do all of the actual work.

I suspect that the recent version catalogs feature could queried within a `resolutionStrategy` to decide if a version is acceptable. If not, then we might try to model around it to make it feel as natural with the platform as possible (e.g. by using toml). If that works and it is merely verbose to define this more intelligent `resolutionStrategy`, then we can offer a convenience function like `rejectVersionIf` rather than build out the underlying infrastructure.

**Comment by ben-manes** [comment]
Another aspect to remember is you can break a build into multiple buildscripts. For example [dependencies.gradle](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle) to declare as `compile libraries.caffeine`. You could define all of your rules in a build script and evaluate that, either as a mini program or looping over the externalized constants. The scriptability can make it easy to implement and then review whether to promote that code towards a plugin.

**Comment by mroeppis** [comment]
A few alternatives have been presented so far.

This feature request targets 2 points:
* externalize candidate version rules
* hide rule logic from user

Gradle offers you options to fulfill point 1. However, it's our turn to provide the logic behind candidate selection.

This is where the "Version Rules" file approach from the original _Versions Maven Plugin_ kicks in. Such a file contains only necessary elements:
* g:a library coordinates (group and artifact ID or just one of them)
* explicit version excludes
* version excludes by pattern

If we decide not to offer the requested feature we transfer the responsibility of logic implementation to the user. As a result, a long chain of logical ORs + ANDs is what we see in case of many libraries that must be treated individually. This adds some complexity, even in case of a separate version rules buildscript.

> The scriptability can make it easy to implement and then review whether to promote that code towards a plugin.

From my point of view it is not desirable to write a custom plugin for that purpose. Instead it should be part of the plugin responsible for checking version updates, namely the `gradle-versions-plugin`.

On the other hand, it's probably _not too hard to ignore logical operators_ when reading an externalized rules buildscript. Besides, the effort of implementing additional parsers and interpreters for common file formats like JSON and XML might not justify the slight gain in clarity and usability of the desired version rules file. Plus, we would need to treat task inputs differently, e.g. prioritize a user's `rejectVersionIf` call if no rules input file is specified.

In the end this seems more like a "matter of taste" thing. No matter the approach, there are pros and cons. In my opinion the version rules file would be nice feature, though.

@ben-manes : Thanks for the discussion!

**Comment by ben-manes** [comment]
I believe any version rules support would merely override the `resolutionStrategy`, which is what `rejectVersionIf` also does. Then it wouldn't be compositional, but you might not need that. I think you could trivially build support by doing something like,

```gradle
// Split off from the build logic into dependencyRules.gradle
ext {
  dependencyRules = [
    'com.github.ben-manes.caffeine:caffeine': {
      ignoreVersions: [
        3.0.0
      ],
      ignoreRegex: /2.*/
    }
  ]
}
```

```gradle
apply from: "${rootDir}/gradle/dependencyRules.gradle"

dependencyUpdates.rejectVersionIf {
  def rule = dependencyRules."${it.candidate.group}:${it.candidate.name}"
  if (!rule) {
    return false
  }
  return (rule.ignoreVersions && rule.ignoreVersions.contains(it.candidate.version))
      || (rule.ignoreRegex && (it.candidate.version ==~ rule.ignoreRegex))
}
```

What do you think?

**Comment by mroeppis** [comment]
@ben-manes : I assumed I couldn't win you for this feature. That's why I decided to close the issue. Anyway, I feel obliged to answer your question. So let's open it again.

As for the MWE above, it's definitely a good starting point for rule interpretation logic. There are a few things missing, though:
* global version ignores (explicit + regex)
* have either only group or artifact ID (...at the moment they must be queried pairwise from the map)
* `ignoreRegex` should be a list

So, as you can see the final implementation would be a little bit more sophisticated. Besides, speaking from a user's perspective it wouldn't make me happy to place the code from above in my project's `build.gradle` for several reasons:
* error-prone -> Why risk a bug if I could rely on solid / tested code from the plugin of my choice?
* I have multiple projects not related to each other. If I wanted to use your plugin in all of them I'd start duplicating rule implementation code across projects (...logic that is meant to come from the plugin itself)
* readability: Why would I want the above solution if I could have:
`dependencyUpdates.versionRulesFile = project.file( 'dependencyUpdates/versionRules.json')` ?

I can understand the MWE is trivial from your point of view. And since only developers will touch those build files it shouldn't be an issue for them to write some decent code, should it? And yet, I'd still say: Better "Keep It Safe and Simple".

@ben-manes : Speaking about the Gradle projects I'm working on, they could really need the version rules mechanism from the Versions Maven Plugin. I believe there are other stakeholders as well. So why not give it a try?

**Comment by ben-manes** [comment]
Thanks @mroeppis for thinking through this. You're correct that I am not inclined to implement this myself, but that is because it is not a problem that I personally face to invest the time into. An extension plugin or maybe a contribution would be preferable.

The MWE should show how someone can implement this without much effort. Spec'ing out what the functionality should be, file format, etc is up to the implementor. The point being that the plugin is flexible enough to allow it to be done and doesn't block those efforts. I wanted to show a proof-of-concept for anyone who might be interested in this issue.

As you have a vision and the need, then I encourage you to write a plugin to add this functionality. You can look at the plugins listed in the readme for examples, e.g. the [gradle-versions-filter-plugin](https://github.com/janderssonse/gradle-versions-filter-plugin) is quite simple. We might decide to merge it back later, but you won't be blocked and will have the functionality for your projects.

**Comment by mroeppis** [comment]
Thanks for providing feedback. This is always useful.
If there are no more opinions I'd like to close the issue.

**Comment by ben-manes** [comment]
Okay, closing
