### ISSUE TITLE
docs: rejectVersionIf

### ISSUE THREAD

**Issue by jmfayard** [ben-manes/gradle-versions-plugin#519]
I did a Google Search to see how rejectVersionIf is used in the wild

https://github.com/search?p=1&q=rejectVersionIf+filename%3Abuild.gradle&type=Code

There are lots of people who have copy/pasted exactly what's in the README without realizing that the second call of rejectVersionnIf overwrites the first

```kotlin
tasks.named("dependencyUpdates").configure {
            // reject all non stable versions
            rejectVersionIf {
                isNonStable(candidate.version)
            }
            // disallow release candidates as upgradable versions from stable versions
            rejectVersionIf {
                isNonStable(candidate.version) &amp;&amp; !isNonStable(currentVersion)
            }
}
```

**Comment by ben-manes** [comment]
Thanks for flagging; that is disheartening. I'll split it up into snippets rather than a single code block.

**Comment by jmfayard** [comment]
@ben-manes yes, one has to be very careful and start from the assumption that people will copy/paste whatever you throw at them. I use this at my advantage now by adding a link to the documentation.

The reason I discoverr this particular problem is that I am currently implementing the same `rejectVersionsIf` logic in refreshVersions.
https://github.com/jmfayard/refreshVersions/issues/311

So if I may ask you: did you get any kinid of feedback for this API? Whether positive or negative

**Comment by ben-manes** [comment]
The feedback has only been around defaults, e.g. #440, where users rightfully would prefer to have a single flag to ignore unstable versions. As you know, any defaults are misleading as versions are inconsistently defined throughout the JVM ecosystem. A sometimes correct default provides a false sense of security and removes the responsibility of understanding dependency management. The asks for shorter APIs don't reduce the implied verbosity and add a more confusing one-off setting. The [gradle-versions-filter-plugin](https://github.com/janderssonse/gradle-versions-filter-plugin#gradle-versions-filter-plugin) is a more appropriate response where a user opted into better defaults, but the baseline is not defaulting to an invalid, wishful opinion.

The other feedback would be #510 and friends, where build authors tend to forget that they have a proper programming language to script with. The `rejectVersionsIf` is short and flexible, and the language makes it easy to implement new features that might be useful. When that feature takes shape it is very easy to promote it into a plugin for reuse and to make the build declarative again. But there is a tendency to want the kitchen sink from plugins rather than compose, à la the unix philosophy.

**Comment by jmfayard** [comment]
Thanks a lot  Ben!
