### ISSUE TITLE
revision=release not working

### ISSUE THREAD

**Issue by phraktle** [ben-manes/gradle-versions-plugin#53]
Even though -Drevision=release is specified, dependencyUpdates suggest upgrading to other versions. 

For example:

 - org.mockito:mockito-core [1.10.8 -> 2.0.5-beta]
 - com.google.protobuf:protobuf-java [2.5.0 -> 3.0.0-alpha-2]
 - org.eclipse.jetty:jetty-client [9.2.9.v20150224 -> 9.3.0.M1]

Specifying it in the gradle file doesn't help either:

    dependencyUpdates {
        revision 'release'
    }

(Using  gradle-versions-plugin 0.8 on gradle 2.3)

**Comment by ben-manes** [comment]
Currently we delegate all dependency management and version comparison to Gradle. This is to avoid duplication of logic and simplify integration. This means that the dependency versioning rules that appear to be bugs are actually Gradle's since we only script above their infrastructure.

A challenge is that these technically aren't bugs because those names do not follow the Maven or Ivy versioning strategy. Even if they did, they were released without properly updating the repository metadata which holds this information. For example take a look at Mockito's [maven-metadata.xml](https://repo1.maven.org/maven2/org/mockito/mockito-core/maven-metadata.xml) which states that the beta is the `release` version.

To handle these cases we'd probably need to define resolution rules that can be customized to filter out versions that don't match the Maven or Ivy guidelines that Gradle follows. So unfortunately the revision flag looked really useful when originally writing this plugin, but in practice isn't that valuable. The current plugin releases have focused on being compatible with Gradle versions and hasn't had a lot of active new development.

**Comment by phraktle** [comment]
A thought then would be to have the option of listing the interim versions available since. This would include point releases as well as betas. But at least you could see what you might want to upgrade to :)

**Comment by ben-manes** [comment]
I agree with you. This requires obtaining additional metadata which was not originally available in Gradle. The plugin works by resolving all of the dependencies with the coordinate version of `latest.$revision`. It then compares the versions found against the original resolved set, and prints a report. This doesn't provide a full version listing to make intelligent recommendations with. On the plus side, it lets Gradle's dependency management do all of the work and does not duplicate it poorly (e.g. by directly searching Maven Central).

The improvements in the Gradle api, like artifact queries and resolution rules, may provide the techniques to more accurately guess the upgrade version. With community support I've been maintaining since the initial version and I haven't spent the time to revamp it if one of those techniques makes this possible.

**Comment by ben-manes** [comment]
Fixed in #63. You can now use component selection rules to customize the report.
