### ISSUE TITLE
org.jacoco:org.jacoco.ant dependency not found?

### ISSUE THREAD

**Issue by ColtonIdle** [ben-manes/gradle-versions-plugin#534]
Running this plugin I get an output of:

```
The following dependencies have later milestone versions:
 - org.jacoco:org.jacoco.ant [0.8.3 -> 0.8.7]
     http://jacoco.org
```

but if I do a global search for jacoco, it does not exist. Any ideas why this could be showing. Is it in some cache?

**Comment by ben-manes** [comment]
That might be a hidden dependency from tooling, https://github.com/ben-manes/gradle-versions-plugin/issues/441#issuecomment-722592681. We try to hide those are they make little sense, and remove by [filtering](https://github.com/ben-manes/gradle-versions-plugin/blob/6abff3c6041dd40f6b9ea706792326aebe7044c1/src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy#L303-L304) out any that appear but were not declared on the Gradle configuration. I'm not sure why it showed up in your case unless a plugin added it explicitly.

**Comment by ColtonIdle** [comment]
Okay. I guess it's safe to just disregard it.

**Comment by adarzulfu** [comment]
same issue for me

**Comment by ben-manes** [comment]
you can see if there is anything pulling it in...
```
./gradlew dependencyInsight --dependency "org.jacoco:org.jacoco.ant"
```

**Comment by ColtonIdle** [comment]
I didn't have any luck with the above command, but just ran ./gradlew dependencies. Out of like 10,000 lines the only thing that includes jacoco is this:

```
androidJacocoAnt - The Jacoco agent to use to get coverage data.
\--- org.jacoco:org.jacoco.ant:0.8.3
     +--- org.jacoco:org.jacoco.core:0.8.3
     |    +--- org.ow2.asm:asm:7.0
     |    +--- org.ow2.asm:asm-commons:7.0
     |    |    +--- org.ow2.asm:asm:7.0
     |    |    +--- org.ow2.asm:asm-tree:7.0
     |    |    |    \--- org.ow2.asm:asm:7.0
     |    |    \--- org.ow2.asm:asm-analysis:7.0
     |    |         \--- org.ow2.asm:asm-tree:7.0 (*)
     |    \--- org.ow2.asm:asm-tree:7.0 (*)
     +--- org.jacoco:org.jacoco.report:0.8.3
     |    \--- org.jacoco:org.jacoco.core:0.8.3 (*)
     \--- org.jacoco:org.jacoco.agent:0.8.3
```

Does this mean that every android project just includes jacoco by default and there's nothing we can do to stop gradle-versions-plugin from telling us that it needs to update?

**Comment by ben-manes** [comment]
It appears so. Their [code](https://android.googlesource.com/platform/tools/base/+/268cc82/build-system/gradle/src/main/groovy/com/android/build/gradle/internal/coverage/JacocoPlugin.groovy) create a configuration and add it as a dynamic dependency. This is usually done using [plugin default dependencies](https://docs.gradle.org/current/userguide/implementing_gradle_plugins.html#providing_default_dependencies_for_plugins) which are hidden but overridable.

This plugin scans all of your project's configurations, gathers its dependencies, and resolves them with a dynamic `+` version. Then it compares the original to the dynamic queries to construct a report. Since the Android team created a configuration with dependencies on your project, it gets pulled into our scan and reported on. It isn't scoped in a way to hide it like default dependency seem to.

**Comment by ben-manes** [comment]
> Does this mean that every android project just includes jacoco by default and there's nothing we can do to stop gradle-versions-plugin from telling us that it needs to update?

You could use a resolution strategy to force the version to the declared one, thereby showing it in the up-to-date list which is usually ignored. Something like,
```groovy
rejectVersionIf {
  return (it.candidate.group == 'org.jacoco') && (it.candidate.version != it.currentVersion)
}
```

**Comment by ColtonIdle** [comment]
Thanks @ben-manes 

I think that's enough info to be able to close out this issue. Cheers

**Comment by konstantin-rudoi** [comment]
new information about it https://issuetracker.google.com/issues/236896287?pli=1
