### ISSUE TITLE
Plugin is not compatible with Gradle 2.4-rc-1

### ISSUE THREAD

**Issue by jochenberger** [ben-manes/gradle-versions-plugin#56]
And again, the version comparator internals have changed:
```
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.Version
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.StaticVersionComparator.compare(StaticVersionComparator.java:25)
	at java_util_Comparator$compare.call(Unknown Source)
	at com.github.benmanes.gradle.versions.updates.DependencyUpdates$_composeVersionMapping_closure13.doCall(DependencyUpdates.groovy:178)
```

**Comment by ben-manes** [comment]
Yep! Do you think we should bite the bullet and copy this over, or continue chasing Gradle's internal version? I liked the idea of delegating as much as possible to Gradle's dependency handling, but I know this is getting annoying...

**Comment by jochenberger** [comment]
I have no strong opinion, but I think I'd rather stick with Gradle's version handling features. Of course that will make it much harder (if at all possible) to solve issues like #25 and #53. But I wouldn't like us to have to maintain more code than necessary.

**Comment by ben-manes** [comment]
Oh definitely let Gradle handle the versioning, I only meant embedding a copy of the comparator class. That's merely for sorting the results for reporting. But if its not annoying you then I prefer to tracking versions and leave as much in Gradle's hands as possible.

The versioning problem is due to not having the version history per dependency nor a resolution strategy to filter with beyond the opaque revision labels. You had a few good suggestions for resolving that, but I never got around to experimenting with your ideas.

**Comment by otrosien** [comment]
I would appreciate if you talked to the gradle guys to move some of the internal APIs to public so that we get better API stability and support.

**Comment by jochenberger** [comment]
I guess they won't to that just yet, given how much the API still changes.
But I might have an idea or two how to simplify our code in that area. I'm having a look.

**Comment by ben-manes** [comment]
I've asked multiple times [[1](https://discuss.gradle.org/t/standard-api-for-dependency-version-comparison/235), [2](https://discuss.gradle.org/t/gradle-1-8-rc-1-alternative-to-latestversionsemanticcomparator/7088), [3](https://discuss.gradle.org/t/add-report-to-display-dependency-updates/540/6)] and each time suggested that the Gradle team use the plugin as a template for adding the task natively. Unfortunately they've shown no interest. I never tried sending a pull request with it integrated because I had a painful experience contributing the Scala IDE support (and other bug fixes) due to them not actively managing or accepting pull requests (at that time). The Gradle devs are awesome, but it felt like Guava where when your on the inside changes go in quick but once your outside its pulling teeth. Eventually you just make do.

**Comment by jochenberger** [comment]
Fix is almost done, I've changed the code to use a try-catch approach to create the comparator. I hope that will make it easier to add new mechanisms in the future. Unfortunately I'll have to remove some of your tests Ben, because the code that they test is gone. ;-)

**Comment by ben-manes** [comment]
I like deleting code more than writing code, so good job =)

**Comment by jochenberger** [comment]
I hope that'll do it, at least it works with 2.0, 2.3 and 2.4-rc-1. Anything else that should go into 0.9?

**Comment by ben-manes** [comment]
Nope, thanks! I'd look at #36 but the sample is 404. None of the other issues are real problems, just embarrassing.
