### ISSUE TITLE
Question: Setup outputFormatter using Closure in Kotlin

### ISSUE THREAD

**Issue by jmpaya** [ben-manes/gradle-versions-plugin#584]
I am having problems setting up the outputFormatter property using a Close in Kotlin scripts.

This is the configuration I am using right now...

```kotlin
tasks.withType<DependencyUpdatesTask> {
    gradleReleaseChannel = "current"
    rejectVersionIf {
        isNonStable(candidate.version) && !isNonStable(currentVersion)
    }
    outputFormatter = { result: com.github.benmanes.gradle.versions.reporter.result.Result ->
        val updatable = result.outdated.dependencies
        if (!updatable.isEmpty()) {
            val writer = StringWriter()
            updatable.forEach { dep ->
                writer.write("> ${dep.group}:${dep.name}: ${dep.version} -> ${dep.available.release ?: dep.available.milestone}")
            }
            println(writer.toString())
        }
    }
}
```

... and the error I'm getting:
```
Cannot handle output formatter (com.github.benmanes.gradle.versions.reporter.result.Result) -> kotlin.Unit, unsupported type
```

I didn't find a complete example using Kotlin, any clue?

**Comment by ben-manes** [comment]
I'm not very familiar with Kotlin so I can try this evening (PST). As that was added in the Groovy only days (as written for Gradle 1.0, and we didn't know Groovy), it checks if Groovy's `Closure` type when executing. It may be that we need to provide a proper setter that accepts an `Action` so that it will infer correctly and work with Kotlin. See the [task](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy) and [usage](https://github.com/ben-manes/gradle-versions-plugin/blob/d22df470960b6400d9451f615a9e9b460407ec04/src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy#L88) (PRs are welcome).

**Comment by jpaya17** [comment]
Thanks @ben-manes. Give it a try when you find a gap because maybe I’m doing something wrong. I did review those source codes but didn’t make it work, so I did prefer asking here, maybe someone found the way.

**Comment by jpaya17** [comment]
Thanks a lot @ben-manes. This is definitely what I was looking for. I'll give it a try to the enhancement that you suggested and try to raise a PR.
