### ISSUE TITLE
failOnDynamicVersions() prevents fetching latest version

### ISSUE THREAD

**Issue by keykey7** [ben-manes/gradle-versions-plugin#592]
preventing dynamic version updates for configurations as in https://docs.gradle.org/current/userguide/resolution_strategy_tuning.html#reproducible-resolution prevents `dependencyUpdates` from fetching the latest versions of all dependencies.
```
configurations.all {
    resolutionStrategy {
        failOnDynamicVersions()
    }
}
```
is there a recommended workaround or can the (global) resolution strategy be disabled just for the configurations added by the `Resolver`? :crystal_ball:

**Comment by ben-manes** [comment]
Usually you can get around this by conditionalizing the your resolution strategy to no-op if the `dependencyUpdate` task will be run. The simplest is checking for it in`gradle.startParameter.taskNames`, with a fancier version being to use `gradle.taskGraph.whenReady`. I think the latter might not work since Gradle 7.0 as I recall them making things stricter.
