### ISSUE TITLE
Shows buildscript dependencies not project dependencies

### ISSUE THREAD

**Issue by shevek** [ben-manes/gradle-versions-plugin#62]
Since updating from gradle 2.2.1 and plugin version 0.4 to gradle 2.4 and plugin version 0.10.1, I seem to see the updates to the buildscript dependencies, not those of the project itself?

**Comment by shevek** [comment]
Test case here: https://github.com/shevek/gradle-stdproject-plugin
Run `./gradlew dependencyUpdates`
Beware confusion: Build script deps are very similar to project deps. However, setting one to gradle-git 1.0.0 and the other to 1.2.0, I only see the updates for the buildscript, not the project.

**Comment by shevek** [comment]
Note: On other projects where the deps do not overlap, it does work, so is this something to do with not reporting correctly if a buildscript dep is the same as a project dep, but of a newer version?

**Comment by ben-manes** [comment]
I'll try to take a look at this tonight and convert your test case into a Spock unit test.

If I understand correctly, you have two dependencies with the same coordinates but different versions. One is up to date and the other isn't, and you expect the report to flag the outdated version? If that is correct then then I'm surprised it ever reported correctly because it globs all of the dependencies into a detached configuration for resolution. The normal dependency logic of taking the greatest version in a dependency set would apply.

**Comment by shevek** [comment]
I do have two dependencies with the same coordinates and different versions, but they're also in different configurations: One's in the buildscript and one's in the compile scope. The test case should explain more, I think it's simple enough.

dependencyUpdates is working fine for other projects, so the question is "Why are buildscript dependencies leaking into project.compile dependencies"?

**Comment by ben-manes** [comment]
Right, this is because the associated configurations are ignored. The plugin aggregates all of the repositories and dependencies across all configurations, adds them to a detached configuration, resolves that, and generates a report.

On the plus side this approach is very simple and covers the common usage. It leverages rather than replicates Gradle's dependency management. The flaws are that Gradle masks version skew (as it chooses the latest declared), does not use the configuration's resolution rules, and does not provide access to the full version history to apply custom filters when versions do follow the Maven/Ivy standard (e.g. "2.0-beta").

I think that instead of aggregating to a detached configuration, we could resolve every configuration and flatten that into a single report. The dependency cache should make this fast by only performing the external lookup once. Then resolution rules are honored and the duplicate coordinates are listed per version.

**Comment by ben-manes** [comment]
#63 resolves this (unit test confirms). Each distinct version will be listed separately, so you might see one reported for upgrade and the other listed at the latest.

**Comment by ben-manes** [comment]
Fixed in #63
