### ISSUE TITLE
com.thoughtworks.xstream:xstream:1.4.17 has a security vulnerability

### ISSUE THREAD

**Issue by bh-tt** [ben-manes/gradle-versions-plugin#698]
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-40156

The fix (>= 1.4.19) appears to be a patch release so it should have little impact.

**Comment by ben-manes** [comment]
This is fixed on master but not released. However your best bet is to use constraints to force transitive dependencies upwards rather than waiting for dependencies to catch up.

An example,
1. https://github.com/ben-manes/caffeine/blob/29081080ea4e8f313706c0cf0d408e8b060285d6/build.gradle#L24
2. https://github.com/ben-manes/caffeine/blob/29081080ea4e8f313706c0cf0d408e8b060285d6/gradle/dependencies.gradle#L265

**Comment by bh-tt** [comment]
Thank you for the quick response, what is estimated next release date?

**Comment by ben-manes** [comment]
There is none planned. The only change that I recall is a rewrite from Groovy to kotlin, but not functionality differences. We are not impacted by this flaw in our usage, so there isn’t any reason to cut a release.

**Comment by bh-tt** [comment]
Thank you, I'll close this.
