### ISSUE TITLE
Group the output by module

### ISSUE THREAD

**Issue by robbypond** [ben-manes/gradle-versions-plugin#70]
When there are several modules in a project, it would be helpful if the dependencies were grouped by module.

**Comment by ben-manes** [comment]
You can do this a little more manually by running the task on a subproject, which is scoped to its subtree. By default the expectation is to run it at the root for a global analysis.

A negative of this request is that the output could seem verbose for centrally managed dependencies. For example if all dependencies are defined in `gradle/dependencies.gradle` so build files can state `compile libraries.guava` instead of copy-n-paste the coordinate string. Similarly if an `allprojects` or `subprojects` block is used to add common dependencies, like a junit testCompile. Both would result in redundant entries where the existing flat view is preferred.

I think this might be better as an alternative console report option. The reporting logic needs a rewrite, something I hope to get to after I fine tune the resolution improvements.

**Comment by vanniktech** [comment]
I'll close this since to me it seems like this has been answered and there's a workaround for this. Maybe there's even something better given that this issue is almost 3 years old. In case you don't agree simple reply to this issue or open a new one.
