### ISSUE TITLE
Publish scm url

### ISSUE THREAD

**Issue by simPod** [ben-manes/gradle-versions-plugin#709]
Can you specify scm url in published releases? Like

```xml
  <scm>
    <connection>scm:git:git://github.com/apollographql/apollo-kotlin.git</connection>
    <developerConnection>scm:git:ssh://git@github.com/apollographql/apollo-kotlin.git</developerConnection>
    <url>https://github.com/apollographql/apollo-kotlin/</url>
  </scm>
```

(https://plugins-artifacts.gradle.org/com.apollographql.apollo3/apollo-gradle-plugin/3.7.0/18ae5b7f7710eacf942b913893f1c8166d236e8ad6eaa7ddafe2bf82f0e26ed8/apollo-gradle-plugin-3.7.0.pom)

Renovate can then read the release notes based on it.

**Comment by ben-manes** [comment]
These are provided below and I see that block in the published [pom](https://plugins.gradle.org/m2/com/github/ben-manes/gradle-versions-plugin/0.44.0/gradle-versions-plugin-0.44.0.pom).
https://github.com/ben-manes/gradle-versions-plugin/blob/4e8ee755ef83903eb6af6ac6456c0c5b9f3ebaa4/gradle.properties#L11-L13

However it might be impacted by how you declare the plugin as there are two coordinate styles. For compatibility Gradle generates the maven style and their own form, the latter of which simply declares the former as a dependency. Since it is then a transitive dependency and the generated pom does not include this information, the tooling wouldn't be able to report it for you ([example](https://plugins.gradle.org/m2/com/github/ben-manes.versions/com.github.ben-manes.versions.gradle.plugin/0.44.0/com.github.ben-manes.versions.gradle.plugin-0.44.0.pom)). That would be a Gradle bug to copy the pom metadata onto the alternative's shim.

**Comment by ben-manes** [comment]
See [Plugin Marker Artifacts](https://docs.gradle.org/current/userguide/plugins.html#sec:plugin_markers) for a little more detail on this other pom file.

**Comment by simPod** [comment]
Thanks for explaining
