### ISSUE TITLE
AGP gradle:8.0.0-alpha09 (released today) doesn't seem to play nice with this plugin

### ISSUE THREAD

**Issue by ColtonIdle** [ben-manes/gradle-versions-plugin#713]
```
⡀ Checking for upgrades

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> 
com.android.builder.errors.EvalIssueException: Product Flavor 'production' contains custom BuildConfig fields, but the feature is disabled.
```

I'm still investigating myself, but if I rollback to alpha08 then everything is fine.

**Comment by ben-manes** [comment]
I don't know why it would fail a build. If the report has errors then it logs them and should never cause a build failure, so that seems unrelated. Otherwise I know that android and kotlin heavily abuse Gradle and metadata so it can be very frustrating because they are not good citizens. They touch internals, break apis, make ad hoc / brittle duplicates of core features, etc. rather than follow conventions. In those cases there is only so much we can do to patch over their poor engineering.

**Comment by ColtonIdle** [comment]
Going to close. looks like AGP is disabling buildConfig generation by default and so you have to go in and manually enable it, even for an app module.
