### ISSUE TITLE
Deprecation warning: Resolution of the configuration :xxx:classpathCopy was attempted from a context different than the project context

### ISSUE THREAD

**Issue by tribbloid** [ben-manes/gradle-versions-plugin#729]
Observed in both version 0.45.0 and 0.44.0, here 0.44.0 was used to avoid triggering:

https://github.com/ben-manes/gradle-versions-plugin/issues/727

Can only be visible if "--warning-mode all" is enabled:

```
$ ./gradlew dependencyUpdates --warning-mode all

...
Resolution of the configuration :xxx:classpathCopy was attempted from a context different than the project context. Have a look at the documentation to understand why this is a problem and how it can be resolved. This behavior has been deprecated. This will fail with an error in Gradle 9.0. See https://docs.gradle.org/8.0/userguide/viewing_debugging_dependencies.html#sub:resolving-unsafe-configuration-resolution-errors for more details.
...
```

No stacktrace or pointer to part of the source code was in the error message. I assume this will be improved in Gradle 9.0. But ideally the plugin could be fixed before that

**Comment by ben-manes** [comment]
haha, you opened this in https://github.com/ben-manes/gradle-versions-plugin/issues/680 👋 

It's been a warning since Gradle 5, but a major change to migrate and not pressing concern for them to break the ecosystem. For now it is to guide new plugins, though PRs are welcome is anyone wants to try reworking ours.
