### ISSUE TITLE
Difference between IntelliJ and Android Studio

### ISSUE THREAD

**Issue by DaRolla** [ben-manes/gradle-versions-plugin#78]
Hi there,

thanks a lot for this plugin, I use it a lot.

But there is something wrong concerning Android Support library which is part of the SDK.

In my build.gradle in the dependecies

    compile 'com.android.support:recyclerview-v7:23.0.0'
    compile 'com.android.support:support-v4:23.0.0'

leads to differences between Android Studio and IntelliJ.

Android Studio:

    The following dependencies exceed the version found at the milestone revision level:
     - com.android.support:recyclerview-v7 [23.0.0 <- 22.0.0]
     - com.android.support:support-v4 [23.0.0 <- 22.0.0]      

IntelliJ:

    The following dependencies have later milestone versions:
     - com.android.support:recyclerview-v7 [23.0.0 -> 23.0.1]
     - com.android.support:support-v4 [23.0.0 -> 23.0.1]

Greetings,
DaRolla

**Comment by ben-manes** [comment]
Can you try using `--info` to see the repositories listed? There's probably a difference.

**Comment by ben-manes** [comment]
I suspect the problem is because you have two different SDK locations. One IDE is set to your project's, another to its own. I think the SDKs are registered as local file repositories, so different repositories are being seen depending on the environment. It'll be something about your repositories and how Google hacked Gradle in non-standard ways, I'm just not sure what.

I'm not an Android developer and wrote this for server-side Java, prior to Android's adoption. I've had to fight with Android a bit and I'm not a fan, so its not my forte. Someone else who knows Android can probably understands better what's going on.

**Comment by ben-manes** [comment]
Resolved when fixing #66 (duplicate)
