### ISSUE TITLE
Using configureAll instead of all causes dependencyUpdates to fail silently

### ISSUE THREAD

**Issue by jimshowalter** [ben-manes/gradle-versions-plugin#801]
We tried to change this:

`dependencyUpdates.resolutionStrategy {
    componentSelection {
        all {`

to this:

`dependencyUpdates.resolutionStrategy {
    componentSelection {
        configureEach {`

because IntelliJ said to do that.

But with the change, dependencyUpdates doesn't output any updates, even when there are updates.

**Comment by ben-manes** [comment]
you can use `-i` to see if an exception was logged. We [pass](https://github.com/ben-manes/gradle-versions-plugin/blob/610f5b2e81923cbbd4e4df0ae6a91bfc414d794e/gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt#L247-L256) your lambda into `configuration.resolutionStrategy` so it's all Gradle's code instead of ours at that point.

**Comment by ben-manes** [comment]
fwiw, I don't see `configureEach` in the Javadoc for [componentSelection](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/ComponentSelectionRules.html).

**Comment by jimshowalter** [comment]
`Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method configureEach() for arguments [dependency_1m5034kjkgp6cdvjn4xjpdx3l$_run_closure4$_closure9$_closure10@31837593] on object of type com.github.benmanes.gradle.versions.updates.resolutionstrategy.ResolutionStrategyWithCurrent.
`

**Comment by ben-manes** [comment]
yep, sounds like you got bamboozled!
