### ISSUE TITLE
ignore rc releases

### ISSUE THREAD

**Issue by christophsturm** [ben-manes/gradle-versions-plugin#85]
Is it possible to ignore rc releases?

<pre>
./gradlew dependencyUpdates -Drevision=release
...
The following dependencies have later release versions:
 - com.fasterxml.jackson.core:jackson-annotations [2.6.3 -> 2.7.0-rc1]
 - com.fasterxml.jackson.core:jackson-core [2.6.3 -> 2.7.0-rc1]
 - com.fasterxml.jackson.core:jackson-databind [2.6.3 -> 2.7.0-rc1]
</pre>

**Comment by ben-manes** [comment]
Its possible using a `resolutionStrategy` (see example in the README). However that is presently scoped to a configuration, e.g. `all`, so it impacts any resolution. A backlog task is to provide one for use by this plugin only, so that you can have an RC dependency in your built but filter it in the upgrade search.

**Comment by henrik242** [comment]
Ref #68

**Comment by ben-manes** [comment]
Fixed
