### ISSUE TITLE
new gradle plugin version syntax plugin not found in any of the following repositories

### ISSUE THREAD

**Issue by sreich** [ben-manes/gradle-versions-plugin#86]
```
* What went wrong:
Plugin [id: 'com.gitub.ben-manes.versions', version: '0.11.3'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (no 'com.gitub.ben-manes.versions' plugin available - see https://plugins.gradle.org for available plugins)
```

my build.gradle contains:
```
plugins {
    id 'com.gitub.ben-manes.versions' version '0.11.3'
}
```
as was recommended by the new gradle plugin syntax documentation.

I cannot fathom why this might be, because as you can see the plugin shows up here and recommends this to me: https://plugins.gradle.org/plugin/com.github.ben-manes.versions

obviously, i'd really like to take advantage of the new, much cleaner syntax..but i'm really curious now why this is the case for this one plugin.

**Comment by ben-manes** [comment]
That's interesting. I'll try to reproduce this evening. I didn't have much luck with the new syntax because many plugins aren't published on the portal and it does not support additional repositories. I feel like its not a finished feature.

I personally prefer [centralizing](https://github.com/ben-manes/caffeine/blob/master/gradle/dependencies.gradle) all my dependencies so that they are not copy-pasted between sub-projects and versions can be easily updated. That leads to a pretty [short buildscript](https://github.com/ben-manes/caffeine/blob/master/build.gradle).

**Comment by ben-manes** [comment]
I experimented and was unable to reproduce your results. I then realized you had a typo! :-)

id 'com.**gitub**.ben-manes.versions' version '0.11.3'

**Comment by sreich** [comment]
Hahaha Oh man. Well that's just embarrassing. Thanks for your time. 

We shall never speak of this again ;)
