### ISSUE TITLE
Per-dependency revision switch?

### ISSUE THREAD

**Issue by the4yeast** [ben-manes/gradle-versions-plugin#89]
Is it possible (in any way, directly or with a workaround) to specify the revision parameter separately for each dependency? That could also override the command line setting.

Ideally, I'd like the plugin to check for new releases for some of my dependencies, but for new milestones for others.

**Comment by ben-manes** [comment]
I've tried to avoid a lot of ad hoc flags or rewrite Gradle's excellent dependency management, and instead simply script on top of the apis. So the most natural hook seems to be [resolutionStrategy](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html) as a way of specifying selection rules. That's used in Gradle's examples to lock down dependencies to specific versions, and in our README for how to filter out beta versions (since that's not a concept in Maven's conventions).

The `resolutionStrategy` support works, but its verbose and global. Ideally we should let users scope it only to the `depenencyUpdates` task rather than be applied to all of your build. Alternatively for rejecting based on a simple version patterns, like `-beta`, a one liner would be provided to avoid the noise. Anyways, that strategy should work for your needs, but it could be friendlier.

I haven't been actively working on this plugin lately, so its in a bit of a flux.

**Comment by the4yeast** [comment]
Thanks for your feedback @ben-manes.
I'll look at ``resolutionStrategy`` then.

Feel free to close this one!
