### ISSUE TITLE
Its take a long time to run checkDependecyUpdate Task

### ISSUE THREAD

**Issue by Hoangkute123xyz** [ben-manes/gradle-versions-plugin#900]
<img width="789" alt="Screenshot 2024-08-14 at 13 10 06" src="https://github.com/user-attachments/assets/2722bd0d-9749-42cd-8020-4b715fa486b9">

**Comment by ben-manes** [comment]
You probably want to use repository [content filtering](https://docs.gradle.org/current/userguide/declaring_repositories.html#sec:repository-content-filtering). Typically this happens because you have something like a snapshot repository in your listing, but also run the task to select release versions. As this plugin scripts Gradle's own dependency management, the resolution rule then evaluates from the latest version to select a candidate, thus evaluating many snapshots. By targeting the resolution you avoid long execution times.

The other problem is that Gradle does resolution sequentially instead of in parallel. They haven't fixed that in over a decade since it doesn't effect most build scenarios. The alternative is to forgo Gradle's own resolution and do it manually, thus not honoring build configuration like constraints. In those cases dependabot is a quite nice alternative (using [dependency-submission](https://github.com/gradle/actions/blob/main/dependency-submission/README.md)).

**Comment by ben-manes** [comment]
https://github.com/ben-manes/gradle-versions-plugin/issues/505
