### ISSUE TITLE
Newer version of junit-platform-commons was not detected

### ISSUE THREAD

**Issue by jimshowalter** [ben-manes/gradle-versions-plugin#901]
We update dependencies every couple of weeks, and use your wonderful plugin to determine what to upgrade.

Unfortunately, it didn't detect the 1.11.0 version of https://mvnrepository.com/artifact/org.junit.platform/junit-platform-commons, and so we stayed on 1.10.3.

But that version of junit-platform-commons isn't compatible with the latest version of junit's core, so we got a runtime error.

We reported that error in https://github.com/junit-team/junit5/issues/3933, and the JUnit team explained that we were using a downrev version.

**Comment by ben-manes** [comment]
Can you provide an example build showing this? In a minimal example it does find a version, indicating that maybe a resolution rule or repository is to blame.

```groovy
plugins {
  id "com.github.ben-manes.versions" version "0.51.0"
  id 'java'
}

repositories {
  mavenCentral()
}

dependencies {
  implementation 'org.junit.platform:junit-platform-commons:1.10.3'
}
```

```console
gradlew dU
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :dependencyUpdates

------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.51.0

The following dependencies have later milestone versions:
 - org.junit.platform:junit-platform-commons [1.10.3 -> 1.11.0]
     https://junit.org/junit5/

Gradle release-candidate updates:
 - Gradle: [8.10: UP-TO-DATE]

Generated report file build/dependencyUpdates/report.txt

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 3s
1 actionable task: 1 executed
```

**Comment by jimshowalter** [comment]
Unfortunately no, because when we tried to boil it down to a small test case, the problem went away.

Our dependencies are complicated. We'll take a look at resolution strategy.

Thank you for the quick reply!

**Comment by ben-manes** [comment]
If its the resolution strategy then `--info` can help (but also be confusingly noisy) about the decision to reject the newer version. Sometimes it can even be a plugin adding that restriction, like a BOM, so it may not be as simple as a println in your own definitions.

Otherwise repositories can be a bit annoying where order can matter. This was especially true for JCenter which tended to return stale manifest metadata on a `+` version, but proxy to Central for a point version it did not contain. If Gradle did not evaluate all repositories, it could return false information leading to a missing option. Since JCenter is defunct its worth ensuring its eradicated from your build as it was a source of many problems due to their flagrant violation of basic repository tenants.

**Comment by jimshowalter** [comment]
We eradicated jcenter last year, so that's not it. Thank you for helping!
