### ISSUE TITLE
Dependency level vision

### ISSUE THREAD

**Issue by Senriel** [ben-manes/gradle-versions-plugin#95]
Hello, 

Is it possible to check dependency level ? Because i can't catch the version I want to check.
I want to see the latest minor level version like 2.4.5 -> 2.6.2 and not 2.4.5 -> 3.0.1

**Comment by ben-manes** [comment]
You can use a resolution strategy to reject any candidate that is not of the same major version. That would reject 3.0.1, then 3.0.0, and then accept 2.6.2.

#69 would provide breadcrumbs where @jochenberger suggested a nice implementation approach (evaluate x.y.+, x.+, and +) such that the report would show [2.4.0 -> 2.4.5 -> 2.6.2 -> 3.0.1]. Unfortunately due to Gradle resolving dependencies sequentially this would make the task slower, so it is on the back burner. When parallel resolution is supported then I think it would be a nice addition.

**Comment by Senriel** [comment]
Oh ok. Tanks a lot.

**Comment by vanniktech** [comment]
We'll get even better once #96 - or any other of the related issues - are done. Hence I'm closing this.
