### ISSUE TITLE
Support providing alternate repositories for version lookup

### ISSUE THREAD

**Issue by JakeWharton** [ben-manes/gradle-versions-plugin#98]
We use Sonatype Nexus as read-through proxy for Maven Central and other external repositories. As such, all our builds only point at that internal proxy and it only contains the versions that have been previously requested.

It would be great if we could specify additional repositories for looking up versions of artifacts. This would let us look at versions in the upstream repo but still only fetch our actual dependencies through the proxy.

Maybe something like:
```groovy
dependencyUpdates {
  repositories += [mavenCentral(), 'http://example.com/repo/']
}
```

**Comment by ben-manes** [comment]
I've done the same previously with Artifactory's virtual repository. It would query the backing repositories to search, cache within a short time frame, and I hadn't observed any issues. It sounds like a bug in Sonatype or the configuration, since Maven's `versions:display-dependency-updates` uses a similar lookup strategy. 

Unfortunately Gradle's [RepositoryHandler](https://docs.gradle.org/current/javadoc/org/gradle/api/artifacts/dsl/RepositoryHandler.html) is extremely buggy due to its [flawed deduping](https://discuss.gradle.org/t/repository-duduping/10327/3). That results in either dropping repositories on a "name" conflict or adding the same multiple times and slowing the resolution. Previously I aggregated all repositories found to cast the widest net, but because of that I refrain from touching it. Instead I use whatever is associated with the configuration. So adding this would probably require trying to work around this bug and might be error prone.

Since repositories are strictly coupled into configuration phase, you can do this yourself dynamically. You might still run into the deduping bug, so I'd name all of your additions explicitly.

```gradle
tasks.dependencyUpdates.doFirst {
  repositories {
    maven { url 'https://a.b.c' }
  }
}
```

```
$ gradle dU -i
...
Resolving caffeine project (root) configurations with repositories:
 - maven: https://jitpack.io
 - MavenRepo: https://repo1.maven.org/maven2/
 - BintrayJCenter: https://jcenter.bintray.com/
 - maven2: https://a.b.c
```

**Comment by JakeWharton** [comment]
Great tip. I'll give it a try.

**Comment by ben-manes** [comment]
wonderful, really glad that worked out for you
